In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import datetime

In [2]:
df = pd.read_csv("DailyData/201301/CN-Reanalysis-daily-2013010100.csv")

In [4]:
df.columns

Index(['PM2.5(微克每立方米)', ' PM10(微克每立方米)', ' SO2(微克每立方米)', ' NO2(微克每立方米)',
       ' CO(毫克每立方米)', ' O3(微克每立方米)', ' U(m/s)', ' V(m/s)', ' TEMP(K)',
       ' RH(%)', ' PSFC(Pa)', ' lat', ' lon', ' '],
      dtype='object')

In [9]:
df.drop(columns=[' '],inplace=True)

In [13]:
df.columns = ['PM2.5', 'PM10', 'SO2', 'NO2',
       'CO', 'O3', 'U', 'V', 'TEMP',
       'RH', 'PSFC', 'lat', 'lon']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42249 entries, 0 to 42248
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PM2.5   42249 non-null  float64
 1   PM10    42249 non-null  float64
 2   SO2     42249 non-null  float64
 3   NO2     42249 non-null  float64
 4   CO      42249 non-null  float64
 5   O3      42249 non-null  float64
 6   U       42249 non-null  float64
 7   V       42249 non-null  float64
 8   TEMP    42249 non-null  float64
 9   RH      42249 non-null  float64
 10  PSFC    42249 non-null  float64
 11  lat     42249 non-null  float64
 12  lon     42249 non-null  float64
dtypes: float64(13)
memory usage: 4.2 MB

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine('mysql+pymysql://root:12345678@localhost:3306/chinavis')

In [20]:
df['date'] = pd.to_datetime("20130101")

In [21]:
df

,PM2.5,PM10,SO2,NO2,CO,O3,U,V,TEMP,RH,PSFC,lat,lon,date
0,20.21,23.56,8.65,4.58,0.29,63.44,-2.48,-2.31,291.54,68.14,100350.11,18.34,109.25,2013-01-01
1,20.41,23.96,9.28,5.24,0.29,62.53,-3.43,-3.21,291.96,67.41,100546.63,18.34,109.38,2013-01-01
2,21.17,24.78,10.07,5.47,0.30,62.24,-3.43,-4.72,291.37,69.59,100428.13,18.33,109.52,2013-01-01
3,22.24,26.04,10.36,5.28,0.30,63.58,-2.92,-5.32,290.74,72.94,100569.27,18.33,109.66,2013-01-01
4,19.68,22.34,7.62,3.58,0.29,66.21,-2.51,-3.13,291.67,65.97,101620.34,18.49,108.83,2013-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42244,0.23,0.26,0.51,0.57,0.22,63.67,5.14,-4.29,246.32,57.99,98157.16,53.18,125.08,2013-01-01
42245,0.13,0.15,1.46,0.52,0.22,63.09,2.99,-5.34,245.23,59.83,96514.89,53.51,123.24,2013-01-01
42246,0.14,0.16,1.51,0.56,0.22,63.93,3.49,-6.46,245.50,57.22,96618.52,53.49,123.45,2013-01-01
42247,0.15,0.18,1.27,0.60,0.22,64.56,3.63,-6.44,246.06,54.63,97171.19,53.47,123.66,2013-01-01
42248,0.17,0.20,1.12,0.70,0.22,64.88,3.85,-6.27,246.37,53.44,97647.19,53.44,123.87,2013-01-01

In [22]:
df.to_sql('daily20130101', engine, index= False)

In [39]:
sql = '''select * from capital_location;'''
cap = pd.read_sql_query(sql, engine)
cap

    name     lon    lat
0     上海  121.53  31.20
1   乌鲁木齐   87.67  43.71
2     兰州  103.74  35.97
3     北京  116.38  39.97
4     南京  118.77  32.09
5     南宁  108.28  22.91
6     南昌  115.93  28.68
7     台北  121.52  25.03
8     合肥  117.28  31.83
9   呼和浩特  111.68  40.82
10   哈尔滨  126.66  45.71
11    天津  117.13  39.09
12    太原  112.48  37.93
13    广州  113.26  23.20
14    成都  104.13  30.66
15    拉萨   91.07  30.01
16    昆明  102.69  25.08
17    杭州  120.24  30.27
18    武汉  114.25  30.59
19    沈阳  123.38  41.81
20    济南  116.95  36.65
21    海口  110.31  20.02
22    澳门  113.32  22.12
23   石家庄  114.56  38.07
24    福州  119.28  26.14
25    西宁  101.70  36.61
26    西安  108.87  34.28
27    贵阳  106.74  26.58
28    郑州  113.70  34.73
29    重庆  106.48  29.57
30    银川  106.30  38.41
31    长春  125.37  43.86
32    长沙  112.94  28.23
33    香港  114.08  22.46

In [40]:
intersected_df = pd.merge(df, cap, on=['lat','lon'], how='inner')
intersected_df

,PM2.5,PM10,SO2,NO2,CO,O3,U,V,TEMP,RH,PSFC,lat,lon,date,name
0,35.35,55.60,14.53,24.35,0.33,56.13,-4.30,-4.32,290.64,75.09,101646.27,20.02,110.31,2013-01-01,海口
1,53.11,85.48,32.69,69.36,1.34,23.06,-0.21,-6.58,285.15,47.11,101968.33,22.12,113.32,2013-01-01,澳门
2,56.72,93.46,17.49,70.10,1.34,13.94,-2.46,-5.45,284.00,39.27,101274.27,22.46,114.08,2013-01-01,香港
3,98.35,111.93,52.38,58.32,1.33,22.49,-2.21,-2.30,282.83,39.36,100637.87,22.91,108.28,2013-01-01,南宁
4,49.91,71.65,31.70,72.06,1.33,14.31,-0.68,-4.29,282.56,42.57,101818.73,23.20,113.26,2013-01-01,广州
5,66.00,121.43,58.20,51.16,2.12,25.55,5.56,2.69,279.64,89.00,80066.09,25.08,102.69,2013-01-01,昆明
6,21.21,25.86,11.08,17.36,0.29,54.10,-5.35,-0.93,285.59,81.34,99618.08,25.03,121.52,2013-01-01,台北
7,78.74,148.85,116.38,48.60,1.54,27.36,0.50,2.06,277.02,57.44,88621.26,26.58,106.74,2013-01-01,贵阳
8,54.01,105.72,13.09,52.18,0.82,9.55,-1.92,-5.17,281.52,58.31,99487.06,26.14,119.28,2013-01-01,福州
9,77.96,106.94,89.93,69.47,1.75,17.21,-0.41,1.15,277.06,50.11,101834.88,28.23,112.94,2013-01-01,长沙
10,86.79,151.89,54.70,59.58,1.76,27.97,0.57,0.67,275.91,53.48,102259.18,28.68,115.93,2013-01-01,南昌
11,78.36,141.54,52.73,56.34,1.73,21.70,-2.38,-1.54,279.39,31.06,98714.33,29.57,106.48,2013-01-01,重庆
12,195.99,283.03,99.97,96.52,2.56,14.86,-1.26,0.67,277.17,27.51,95834.08,30.66,104.13,2013-01-01,成都
13,3.28,5.27,0.07,2.45,0.17,78.72,5.35,-2.74,268.42,30.05,57861.72,30.01,91.07,2013-01-01,拉萨
14,75.02,115.39,77.57,81.11,1.67,15.78,1.19,0.75,277.65,62.61,102260.30,30.59,114.25,2013-01-01,武汉
15,60.96,88.38,35.29,63.41,1.68,16.40,2.22,1.19,277.15,50.98,102410.02,30.27,120.24,2013-01-01,杭州
16,76.29,121.12,51.30,77.72,1.57,12.83,5.63,-0.03,276.40,65.87,102360.29,31.20,121.53,2013-01-01,上海
17,63.58,105.52,27.09,42.29,1.82,14.55,2.29,-1.04,274.94,56.49,102225.02,31.83,117.28,2013-01-01,合肥
18,61.93,129.60,63.64,61.51,1.97,11.89,3.50,-0.10,274.21,65.80,102188.28,32.09,118.77,2013-01-01,南京
19,103.34,179.77,63.54,60.21,2.69,25.05,0.13,0.39,276.52,24.35,97912.80,34.28,108.87,2013-01-01,西安
20,79.27,243.16,60.04,41.61,3.41,26.99,0.61,-3.25,273.11,36.04,101071.23,34.73,113.70,2013-01-01,郑州
21,104.49,140.03,45.01,52.54,2.25,28.05,-2.71,0.24,264.87,43.37,79369.07,35.97,103.74,2013-01-01,兰州
22,82.98,152.88,39.66,28.86,2.98,29.70,-0.61,-0.00,268.50,31.31,75145.72,36.61,101.70,2013-01-01,西宁
23,97.74,217.89,115.47,59.90,1.71,16.83,1.76,-2.88,265.82,54.69,101739.43,36.65,116.95,2013-01-01,济南
24,30.75,47.72,42.33,15.72,7.80,40.10,3.10,-2.88,259.26,48.25,90974.62,37.93,112.48,2013-01-01,太原
25,39.88,101.00,153.98,27.07,1.31,52.26,0.70,-1.30,263.01,50.18,89356.45,38.41,106.30,2013-01-01,银川
26,61.08,243.88,99.15,43.59,1.79,29.43,3.99,-6.81,267.08,28.84,102077.76,38.07,114.56,2013-01-01,石家庄
27,102.70,139.61,102.98,50.04,3.18,29.66,2.26,-7.67,262.03,41.86,102600.95,39.09,117.13,2013-01-01,天津
28,42.89,69.33,44.86,38.34,1.72,32.76,4.36,-5.50,262.00,34.09,102156.66,39.97,116.38,2013-01-01,北京
29,12.67,28.18,27.22,10.19,3.97,59.87,2.47,-3.98,250.94,49.56,88373.59,40.82,111.68,2013-01-01,呼和浩特
30,67.40,103.93,149.82,31.14,2.04,28.85,1.85,-2.98,252.02,66.98,101706.57,41.81,123.38,2013-01-01,沈阳
31,22.51,48.32,9.25,21.55,0.66,57.46,-5.42,5.21,269.93,25.39,89221.05,43.71,87.67,2013-01-01,乌鲁木齐
32,147.69,190.28,96.99,62.61,1.77,28.88,2.91,0.79,242.84,72.80,99092.06,43.86,125.37,2013-01-01,长春
33,251.92,318.15,74.70,83.55,2.50,12.23,1.63,1.04,240.73,70.28,99790.09,45.71,126.66,2013-01-01,哈尔滨

In [41]:
rootPath = "DailyData"
dirlist = []
for fd in os.listdir(rootPath): 
    if os.path.isdir(os.path.join(rootPath,fd)): # not .zip or .DS_Store
        dirlist.append(fd) # 201301
dirlist.sort(key= lambda x:int(x))  #sort by date for MacOS

allCsv = pd.DataFrame(columns=['date','PM2.5', 'PM10', 'SO2', 'NO2',
           'CO', 'O3', 'U(m/s)', 'V(m/s)', 'TEMP(K)',
           'RH(%)', 'PSFC(Pa)','lat','lon'])
for ds in dirlist:
#     print(ds) # 201301 dir
    files = os.listdir(os.path.join(rootPath,ds)) # CN-Reanalysis-daily-2013010100.csv
    files.sort(key= lambda x:int(x[25:28]))  #sort by date for MacOS
  
    for csv in files: 
#         print(csv) # CN-Reanalysis-daily-2013010100.csv
        time = csv.split("-")[-1].split(".")[0]
        date = datetime.date(int(time[:4]), int(time[4:6]), int(time[6:8]))
        print(date)

        csv_data = pd.read_csv(os.path.join(rootPath,ds,csv))
        csv_data = csv_data.drop(columns=[" "])
        csv_data.columns = ['PM2.5', 'PM10', 'SO2', 'NO2',
           'CO', 'O3', 'U(m/s)', 'V(m/s)', 'TEMP(K)',
           'RH(%)', 'PSFC(Pa)','lat','lon']
        csv_data['date'] = date
#         allCsv = allCsv.append(csv_data.loc[0::210],ignore_index=True)

        intersected_df = pd.merge(csv_data, cap, on=['lat','lon'], how='inner')
        allCsv = allCsv.append(intersected_df,ignore_index=True)
    
allCsv.to_csv('PointsCapital.csv',  encoding='utf_8_sig', index=False)

2013-01-01
2013-01-02
2013-01-03
2013-01-04
2013-01-05
2013-01-06
2013-01-07
2013-01-08
2013-01-09
2013-01-10
2013-01-11
2013-01-12
2013-01-13
2013-01-14
2013-01-15
2013-01-16
2013-01-17
2013-01-18
2013-01-19
2013-01-20
2013-01-21
2013-01-22
2013-01-23
2013-01-24
2013-01-25
2013-01-26
2013-01-27
2013-01-28
2013-01-29
2013-01-30
2013-01-31
2013-02-01
2013-02-02
2013-02-03
2013-02-04
2013-02-05
2013-02-06
2013-02-07
2013-02-08
2013-02-09
2013-02-10
2013-02-11
2013-02-12
2013-02-13
2013-02-14
2013-02-15
2013-02-16
2013-02-17
2013-02-18
2013-02-19
2013-02-20
2013-02-21
2013-02-22
2013-02-23
2013-02-24
2013-02-25
2013-02-26
2013-02-27
2013-02-28
2013-03-01
2013-03-02
2013-03-03
2013-03-04
2013-03-05
2013-03-06
2013-03-07
2013-03-08
2013-03-09
2013-03-10
2013-03-11
2013-03-12
2013-03-13
2013-03-14
2013-03-15
2013-03-16
2013-03-17
2013-03-18
2013-03-19
2013-03-20
2013-03-21
2013-03-22
2013-03-23
2013-03-24
2013-03-25
2013-03-26
2013-03-27
2013-03-28
2013-03-29
2013-03-30
2013-03-31
2013-04-01
2013-04-02
2013-04-03
2013-04-04
2013-04-05
2013-04-06
2013-04-07
2013-04-08
2013-04-09
2013-04-10
2013-04-11
2013-04-12
2013-04-13
2013-04-14
2013-04-15
2013-04-16
2013-04-17
2013-04-18
2013-04-19
2013-04-20
2013-04-21
2013-04-22
2013-04-23
2013-04-24
2013-04-25
2013-04-26
2013-04-27
2013-04-28
2013-04-29
2013-04-30
2013-05-01
2013-05-02
2013-05-03
2013-05-04
2013-05-05
2013-05-06
2013-05-07
2013-05-08
2013-05-09
2013-05-10
2013-05-11
2013-05-12
2013-05-13
2013-05-14
2013-05-15
2013-05-16
2013-05-17
2013-05-18
2013-05-19
2013-05-20
2013-05-21
2013-05-22
2013-05-23
2013-05-24
2013-05-25
2013-05-26
2013-05-27
2013-05-28
2013-05-29
2013-05-30
2013-05-31
2013-06-01
2013-06-02
2013-06-03
2013-06-04
2013-06-05
2013-06-06
2013-06-07
2013-06-08
2013-06-09
2013-06-10
2013-06-11
2013-06-12
2013-06-13
2013-06-14
2013-06-15
2013-06-16
2013-06-17
2013-06-18
2013-06-19
2013-06-20
2013-06-21
2013-06-22
2013-06-23
2013-06-24
2013-06-25
2013-06-26
2013-06-27
2013-06-28
2013-06-29
2013-06-30
2013-07-01
2013-07-02
2013-07-03
2013-07-04
2013-07-05
2013-07-06
2013-07-07
2013-07-08
2013-07-09
2013-07-10
2013-07-11
2013-07-12
2013-07-13
2013-07-14
2013-07-15
2013-07-16
2013-07-17
2013-07-18
2013-07-19
2013-07-20
2013-07-21
2013-07-22
2013-07-23
2013-07-24
2013-07-25
2013-07-26
2013-07-27
2013-07-28
2013-07-29
2013-07-30
2013-07-31
2013-08-01
2013-08-02
2013-08-03
2013-08-04
2013-08-05
2013-08-06
2013-08-07
2013-08-08
2013-08-09
2013-08-10
2013-08-11
2013-08-12
2013-08-13
2013-08-14
2013-08-15
2013-08-16
2013-08-17
2013-08-18
2013-08-19
2013-08-20
2013-08-21
2013-08-22
2013-08-23
2013-08-24
2013-08-25
2013-08-26
2013-08-27
2013-08-28
2013-08-29
2013-08-30
2013-08-31
2013-09-01
2013-09-02
2013-09-03
2013-09-04
2013-09-05
2013-09-06
2013-09-07
2013-09-08
2013-09-09
2013-09-10
2013-09-11
2013-09-12
2013-09-13
2013-09-14
2013-09-15
2013-09-16
2013-09-17
2013-09-18
2013-09-19
2013-09-20
2013-09-21
2013-09-22
2013-09-23
2013-09-24
2013-09-25
2013-09-26
2013-09-27
2013-09-28
2013-09-29
2013-09-30
2013-10-01
2013-10-02
2013-10-03
2013-10-04
2013-10-05
2013-10-06
2013-10-07
2013-10-08
2013-10-09
2013-10-10
2013-10-11
2013-10-12
2013-10-13
2013-10-14
2013-10-15
2013-10-16
2013-10-17
2013-10-18
2013-10-19
2013-10-20
2013-10-21
2013-10-22
2013-10-23
2013-10-24
2013-10-25
2013-10-26
2013-10-27
2013-10-28
2013-10-29
2013-10-30
2013-10-31
2013-11-01
2013-11-02
2013-11-03
2013-11-04
2013-11-05
2013-11-06
2013-11-07
2013-11-08
2013-11-09
2013-11-10
2013-11-11
2013-11-12
2013-11-13
2013-11-14
2013-11-15
2013-11-16
2013-11-17
2013-11-18
2013-11-19
2013-11-20
2013-11-21
2013-11-22
2013-11-23
2013-11-24
2013-11-25
2013-11-26
2013-11-27
2013-11-28
2013-11-29
2013-11-30
2013-12-01
2013-12-02
2013-12-03
2013-12-04
2013-12-05
2013-12-06
2013-12-07
2013-12-08
2013-12-09
2013-12-10
2013-12-11
2013-12-12
2013-12-13
2013-12-14
2013-12-15
2013-12-16
2013-12-17
2013-12-18
2013-12-19
2013-12-20
2013-12-21
2013-12-22
2013-12-23
2013-12-24
2013-12-25
2013-12-26
2013-12-27
2013-12-28
2013-12-29
2013-12-30
2013-12-31
2014-01-01
2014-01-02
2014-01-03
2014-01-04
2014-01-05
2014-01-06
2014-01-07
2014-01-08
2014-01-09
2014-01-10
2014-01-11
2014-01-12
2014-01-13
2014-01-14
2014-01-15
2014-01-16
2014-01-17
2014-01-18
2014-01-19
2014-01-20
2014-01-21
2014-01-22
2014-01-23
2014-01-24
2014-01-25
2014-01-26
2014-01-27
2014-01-28
2014-01-29
2014-01-30
2014-01-31
2014-02-01
2014-02-02
2014-02-03
2014-02-04
2014-02-05
2014-02-06
2014-02-07
2014-02-08
2014-02-09
2014-02-10
2014-02-11
2014-02-12
2014-02-13
2014-02-14
2014-02-15
2014-02-16
2014-02-17
2014-02-18
2014-02-19
2014-02-20
2014-02-21
2014-02-22
2014-02-23
2014-02-24
2014-02-25
2014-02-26
2014-02-27
2014-02-28
2014-03-01
2014-03-02
2014-03-03
2014-03-04
2014-03-05
2014-03-06
2014-03-07
2014-03-08
2014-03-09
2014-03-10
2014-03-11
2014-03-12
2014-03-13
2014-03-14
2014-03-15
2014-03-16
2014-03-17
2014-03-18
2014-03-19
2014-03-20
2014-03-21
2014-03-22
2014-03-23
2014-03-24
2014-03-25
2014-03-26
2014-03-27
2014-03-28
2014-03-29
2014-03-30
2014-03-31
2014-04-01
2014-04-02
2014-04-03
2014-04-04
2014-04-05
2014-04-06
2014-04-07
2014-04-08
2014-04-09
2014-04-10
2014-04-11
2014-04-12
2014-04-13
2014-04-14
2014-04-15
2014-04-16
2014-04-17
2014-04-18
2014-04-19
2014-04-20
2014-04-21
2014-04-22
2014-04-23
2014-04-24
2014-04-25
2014-04-26
2014-04-27
2014-04-28
2014-04-29
2014-04-30
2014-05-01
2014-05-02
2014-05-03
2014-05-04
2014-05-05
2014-05-06
2014-05-07
2014-05-08
2014-05-09
2014-05-10
2014-05-11
2014-05-12
2014-05-13
2014-05-14
2014-05-15
2014-05-16
2014-05-17
2014-05-18
2014-05-19
2014-05-20
2014-05-21
2014-05-22
2014-05-23
2014-05-24
2014-05-25
2014-05-26
2014-05-27
2014-05-28
2014-05-29
2014-05-30
2014-05-31
2014-06-01
2014-06-02
2014-06-03
2014-06-04
2014-06-05
2014-06-06
2014-06-07
2014-06-08
2014-06-09
2014-06-10
2014-06-11
2014-06-12
2014-06-13
2014-06-14
2014-06-15
2014-06-16
2014-06-17
2014-06-18
2014-06-19
2014-06-20
2014-06-21
2014-06-22
2014-06-23
2014-06-24
2014-06-25
2014-06-26
2014-06-27
2014-06-28
2014-06-29
2014-06-30
2014-07-01
2014-07-02
2014-07-03
2014-07-04
2014-07-05
2014-07-06
2014-07-07
2014-07-08
2014-07-09
2014-07-10
2014-07-11
2014-07-12
2014-07-13
2014-07-14
2014-07-15
2014-07-16
2014-07-17
2014-07-18
2014-07-19
2014-07-20
2014-07-21
2014-07-22
2014-07-23
2014-07-24
2014-07-25
2014-07-26
2014-07-27
2014-07-28
2014-07-29
2014-07-30
2014-07-31
2014-08-01
2014-08-02
2014-08-03
2014-08-04
2014-08-05
2014-08-06
2014-08-07
2014-08-08
2014-08-09
2014-08-10
2014-08-11
2014-08-12
2014-08-13
2014-08-14
2014-08-15
2014-08-16
2014-08-17
2014-08-18
2014-08-19
2014-08-20
2014-08-21
2014-08-22
2014-08-23
2014-08-24
2014-08-25
2014-08-26
2014-08-27
2014-08-28
2014-08-29
2014-08-30
2014-08-31
2014-09-01
2014-09-02
2014-09-03
2014-09-04
2014-09-05
2014-09-06
2014-09-07
2014-09-08
2014-09-09
2014-09-10
2014-09-11
2014-09-12
2014-09-13
2014-09-14
2014-09-15
2014-09-16
2014-09-17
2014-09-18
2014-09-19
2014-09-20
2014-09-21
2014-09-22
2014-09-23
2014-09-24
2014-09-25
2014-09-26
2014-09-27
2014-09-28
2014-09-29
2014-09-30
2014-10-01
2014-10-02
2014-10-03
2014-10-04
2014-10-05
2014-10-06
2014-10-07
2014-10-08
2014-10-09
2014-10-10
2014-10-11
2014-10-12
2014-10-13
2014-10-14
2014-10-15
2014-10-16
2014-10-17
2014-10-18
2014-10-19
2014-10-20
2014-10-21
2014-10-22
2014-10-23
2014-10-24
2014-10-25
2014-10-26
2014-10-27
2014-10-28
2014-10-29
2014-10-30
2014-10-31
2014-11-01
2014-11-02
2014-11-03
2014-11-04
2014-11-05
2014-11-06
2014-11-07
2014-11-08
2014-11-09
2014-11-10
2014-11-11
2014-11-12
2014-11-13
2014-11-14
2014-11-15
2014-11-16
2014-11-17
2014-11-18
2014-11-19
2014-11-20
2014-11-21
2014-11-22
2014-11-23
2014-11-24
2014-11-25
2014-11-26
2014-11-27
2014-11-28
2014-11-29
2014-11-30
2014-12-01
2014-12-02
2014-12-03
2014-12-04
2014-12-05
2014-12-06
2014-12-07
2014-12-08
2014-12-09
2014-12-10
2014-12-11
2014-12-12
2014-12-13
2014-12-14
2014-12-15
2014-12-16
2014-12-17
2014-12-18
2014-12-19
2014-12-20
2014-12-21
2014-12-22
2014-12-23
2014-12-24
2014-12-25
2014-12-26
2014-12-27
2014-12-28
2014-12-29
2014-12-30
2014-12-31
2015-01-01
2015-01-02
2015-01-03
2015-01-04
2015-01-05
2015-01-06
2015-01-07
2015-01-08
2015-01-09
2015-01-10
2015-01-11
2015-01-12
2015-01-13
2015-01-14
2015-01-15
2015-01-16

2015-01-17
2015-01-18
2015-01-19
2015-01-20
2015-01-21
2015-01-22
2015-01-23
2015-01-24
2015-01-25
2015-01-26
2015-01-27
2015-01-28
2015-01-29
2015-01-30
2015-01-31
2015-02-01
2015-02-02
2015-02-03
2015-02-04
2015-02-05
2015-02-06
2015-02-07
2015-02-08
2015-02-09
2015-02-10
2015-02-11
2015-02-12
2015-02-13
2015-02-14
2015-02-15
2015-02-16
2015-02-17
2015-02-18
2015-02-19
2015-02-20
2015-02-21
2015-02-22
2015-02-23
2015-02-24
2015-02-25
2015-02-26
2015-02-27
2015-02-28
2015-03-01
2015-03-02
2015-03-03
2015-03-04
2015-03-05
2015-03-06
2015-03-07
2015-03-08
2015-03-09
2015-03-10
2015-03-11
2015-03-12
2015-03-13
2015-03-14
2015-03-15
2015-03-16
2015-03-17
2015-03-18
2015-03-19
2015-03-20
2015-03-21
2015-03-22
2015-03-23
2015-03-24
2015-03-25
2015-03-26
2015-03-27
2015-03-28
2015-03-29
2015-03-30
2015-03-31
2015-04-01
2015-04-02
2015-04-03
2015-04-04
2015-04-05
2015-04-06
2015-04-07
2015-04-08
2015-04-09
2015-04-10
2015-04-11
2015-04-12
2015-04-13
2015-04-14
2015-04-15
2015-04-16
2015-04-17
2015-04-18
2015-04-19
2015-04-20
2015-04-21
2015-04-22
2015-04-23
2015-04-24
2015-04-25
2015-04-26
2015-04-27
2015-04-28
2015-04-29
2015-04-30
2015-05-01
2015-05-02
2015-05-03
2015-05-04
2015-05-05
2015-05-06
2015-05-07
2015-05-08
2015-05-09
2015-05-10
2015-05-11
2015-05-12
2015-05-13
2015-05-14
2015-05-15
2015-05-16
2015-05-17
2015-05-18
2015-05-19
2015-05-20
2015-05-21
2015-05-22
2015-05-23
2015-05-24
2015-05-25
2015-05-26
2015-05-27
2015-05-28
2015-05-29
2015-05-30
2015-05-31
2015-06-01
2015-06-02
2015-06-03
2015-06-04
2015-06-05
2015-06-06
2015-06-07
2015-06-08
2015-06-09
2015-06-10
2015-06-11
2015-06-12
2015-06-13
2015-06-14
2015-06-15
2015-06-16
2015-06-17
2015-06-18
2015-06-19
2015-06-20
2015-06-21
2015-06-22
2015-06-23
2015-06-24
2015-06-25
2015-06-26
2015-06-27
2015-06-28
2015-06-29
2015-06-30
2015-07-01
2015-07-02
2015-07-03
2015-07-04
2015-07-05
2015-07-06
2015-07-07
2015-07-08
2015-07-09
2015-07-10
2015-07-11
2015-07-12
2015-07-13
2015-07-14
2015-07-15
2015-07-16
2015-07-17
2015-07-18
2015-07-19
2015-07-20
2015-07-21
2015-07-22
2015-07-23
2015-07-24
2015-07-25
2015-07-26
2015-07-27
2015-07-28
2015-07-29
2015-07-30
2015-07-31
2015-08-01
2015-08-02
2015-08-03
2015-08-04
2015-08-05
2015-08-06
2015-08-07
2015-08-08
2015-08-09
2015-08-10
2015-08-11
2015-08-12
2015-08-13
2015-08-14
2015-08-15
2015-08-16
2015-08-17
2015-08-18
2015-08-19
2015-08-20
2015-08-21
2015-08-22
2015-08-23
2015-08-24
2015-08-25
2015-08-26
2015-08-27
2015-08-28
2015-08-29
2015-08-30
2015-08-31
2015-09-01
2015-09-02
2015-09-03
2015-09-04
2015-09-05
2015-09-06
2015-09-07
2015-09-08
2015-09-09
2015-09-10
2015-09-11
2015-09-12
2015-09-13
2015-09-14
2015-09-15
2015-09-16
2015-09-17
2015-09-18
2015-09-19
2015-09-20
2015-09-21
2015-09-22
2015-09-23
2015-09-24
2015-09-25
2015-09-26
2015-09-27
2015-09-28
2015-09-29
2015-09-30
2015-10-01
2015-10-02
2015-10-03
2015-10-04
2015-10-05
2015-10-06
2015-10-07
2015-10-08
2015-10-09
2015-10-10
2015-10-11
2015-10-12
2015-10-13
2015-10-14
2015-10-15
2015-10-16
2015-10-17
2015-10-18
2015-10-19
2015-10-20
2015-10-21
2015-10-22
2015-10-23
2015-10-24
2015-10-25
2015-10-26
2015-10-27
2015-10-28
2015-10-29
2015-10-30
2015-10-31
2015-11-01
2015-11-02
2015-11-03
2015-11-04
2015-11-05
2015-11-06
2015-11-07
2015-11-08
2015-11-09
2015-11-10
2015-11-11
2015-11-12
2015-11-13
2015-11-14
2015-11-15
2015-11-16
2015-11-17
2015-11-18
2015-11-19
2015-11-20
2015-11-21
2015-11-22
2015-11-23
2015-11-24
2015-11-25
2015-11-26
2015-11-27
2015-11-28
2015-11-29
2015-11-30
2015-12-01
2015-12-02
2015-12-03
2015-12-04
2015-12-05
2015-12-06
2015-12-07
2015-12-08
2015-12-09
2015-12-10
2015-12-11
2015-12-12
2015-12-13
2015-12-14
2015-12-15
2015-12-16
2015-12-17
2015-12-18
2015-12-19
2015-12-20
2015-12-21
2015-12-22
2015-12-23
2015-12-24
2015-12-25
2015-12-26
2015-12-27
2015-12-28
2015-12-29
2015-12-30
2015-12-31
2016-01-01
2016-01-02
2016-01-03
2016-01-04
2016-01-05
2016-01-06
2016-01-07
2016-01-08
2016-01-09
2016-01-10
2016-01-11
2016-01-12
2016-01-13
2016-01-14
2016-01-15
2016-01-16
2016-01-17
2016-01-18
2016-01-19
2016-01-20
2016-01-21
2016-01-22
2016-01-23
2016-01-24
2016-01-25
2016-01-26
2016-01-27
2016-01-28
2016-01-29
2016-01-30
2016-01-31
2016-02-01
2016-02-02
2016-02-03
2016-02-04
2016-02-05
2016-02-06
2016-02-07
2016-02-08
2016-02-09
2016-02-10
2016-02-11
2016-02-12
2016-02-13
2016-02-14
2016-02-15
2016-02-16
2016-02-17
2016-02-18
2016-02-19
2016-02-20
2016-02-21
2016-02-22
2016-02-23
2016-02-24
2016-02-25
2016-02-26
2016-02-27
2016-02-28
2016-02-29
2016-03-01
2016-03-02
2016-03-03
2016-03-04
2016-03-05
2016-03-06
2016-03-07
2016-03-08
2016-03-09
2016-03-10
2016-03-11
2016-03-12
2016-03-13
2016-03-14
2016-03-15
2016-03-16
2016-03-17
2016-03-18
2016-03-19
2016-03-20
2016-03-21
2016-03-22
2016-03-23
2016-03-24
2016-03-25
2016-03-26
2016-03-27
2016-03-28
2016-03-29
2016-03-30
2016-03-31
2016-04-01
2016-04-02
2016-04-03
2016-04-04
2016-04-05
2016-04-06
2016-04-07
2016-04-08
2016-04-09
2016-04-10
2016-04-11
2016-04-12
2016-04-13
2016-04-14
2016-04-15
2016-04-16
2016-04-17
2016-04-18
2016-04-19
2016-04-20
2016-04-21
2016-04-22
2016-04-23
2016-04-24
2016-04-25
2016-04-26
2016-04-27
2016-04-28
2016-04-29
2016-04-30
2016-05-01
2016-05-02
2016-05-03
2016-05-04
2016-05-05
2016-05-06
2016-05-07
2016-05-08
2016-05-09
2016-05-10
2016-05-11
2016-05-12
2016-05-13
2016-05-14
2016-05-15
2016-05-16
2016-05-17
2016-05-18
2016-05-19
2016-05-20
2016-05-21
2016-05-22
2016-05-23
2016-05-24
2016-05-25
2016-05-26
2016-05-27
2016-05-28
2016-05-29
2016-05-30
2016-05-31
2016-06-01
2016-06-02
2016-06-03
2016-06-04
2016-06-05
2016-06-06
2016-06-07
2016-06-08
2016-06-09
2016-06-10
2016-06-11
2016-06-12
2016-06-13
2016-06-14
2016-06-15
2016-06-16
2016-06-17
2016-06-18
2016-06-19
2016-06-20
2016-06-21
2016-06-22
2016-06-23
2016-06-24
2016-06-25
2016-06-26
2016-06-27
2016-06-28
2016-06-29
2016-06-30
2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31
2016-08-01
2016-08-02
2016-08-03
2016-08-04
2016-08-05
2016-08-06
2016-08-07
2016-08-08
2016-08-09
2016-08-10
2016-08-11
2016-08-12
2016-08-13
2016-08-14
2016-08-15
2016-08-16
2016-08-17
2016-08-18
2016-08-19
2016-08-20
2016-08-21
2016-08-22
2016-08-23
2016-08-24
2016-08-25
2016-08-26
2016-08-27
2016-08-28
2016-08-29
2016-08-30
2016-08-31
2016-09-01
2016-09-02
2016-09-03
2016-09-04
2016-09-05
2016-09-06
2016-09-07
2016-09-08
2016-09-09
2016-09-10
2016-09-11
2016-09-12
2016-09-13
2016-09-14
2016-09-15
2016-09-16
2016-09-17
2016-09-18
2016-09-19
2016-09-20
2016-09-21
2016-09-22
2016-09-23
2016-09-24
2016-09-25
2016-09-26
2016-09-27
2016-09-28
2016-09-29
2016-09-30
2016-10-01
2016-10-02
2016-10-03
2016-10-04
2016-10-05
2016-10-06
2016-10-07
2016-10-08
2016-10-09
2016-10-10
2016-10-11
2016-10-12
2016-10-13
2016-10-14
2016-10-15
2016-10-16
2016-10-17
2016-10-18
2016-10-19
2016-10-20
2016-10-21
2016-10-22
2016-10-23
2016-10-24
2016-10-25
2016-10-26
2016-10-27
2016-10-28
2016-10-29
2016-10-30
2016-10-31
2016-11-01
2016-11-02
2016-11-03
2016-11-04
2016-11-05
2016-11-06
2016-11-07
2016-11-08
2016-11-09
2016-11-10
2016-11-11
2016-11-12
2016-11-13
2016-11-14
2016-11-15
2016-11-16
2016-11-17
2016-11-18
2016-11-19
2016-11-20
2016-11-21
2016-11-22
2016-11-23
2016-11-24
2016-11-25
2016-11-26
2016-11-27
2016-11-28
2016-11-29
2016-11-30
2016-12-01
2016-12-02
2016-12-03
2016-12-04
2016-12-05
2016-12-06
2016-12-07
2016-12-08
2016-12-09
2016-12-10
2016-12-11
2016-12-12
2016-12-13
2016-12-14
2016-12-15
2016-12-16
2016-12-17
2016-12-18
2016-12-19
2016-12-20
2016-12-21
2016-12-22
2016-12-23
2016-12-24
2016-12-25
2016-12-26
2016-12-27
2016-12-28
2016-12-29
2016-12-30
2016-12-31
2017-01-01
2017-01-02
2017-01-03
2017-01-04
2017-01-05
2017-01-06
2017-01-07
2017-01-08
2017-01-09
2017-01-10
2017-01-11
2017-01-12
2017-01-13
2017-01-14
2017-01-15
2017-01-16
2017-01-17
2017-01-18
2017-01-19
2017-01-20
2017-01-21
2017-01-22
2017-01-23
2017-01-24
2017-01-25
2017-01-26
2017-01-27
2017-01-28
2017-01-29
2017-01-30
2017-01-31

2017-02-01
2017-02-02
2017-02-03
2017-02-04
2017-02-05
2017-02-06
2017-02-07
2017-02-08
2017-02-09
2017-02-10
2017-02-11
2017-02-12
2017-02-13
2017-02-14
2017-02-15
2017-02-16
2017-02-17
2017-02-18
2017-02-19
2017-02-20
2017-02-21
2017-02-22
2017-02-23
2017-02-24
2017-02-25
2017-02-26
2017-02-27
2017-02-28
2017-03-01
2017-03-02
2017-03-03
2017-03-04
2017-03-05
2017-03-06
2017-03-07
2017-03-08
2017-03-09
2017-03-10
2017-03-11
2017-03-12
2017-03-13
2017-03-14
2017-03-15
2017-03-16
2017-03-17
2017-03-18
2017-03-19
2017-03-20
2017-03-21
2017-03-22
2017-03-23
2017-03-24
2017-03-25
2017-03-26
2017-03-27
2017-03-28
2017-03-29
2017-03-30
2017-03-31
2017-04-01
2017-04-02
2017-04-03
2017-04-04
2017-04-05
2017-04-06
2017-04-07
2017-04-08
2017-04-09
2017-04-10
2017-04-11
2017-04-12
2017-04-13
2017-04-14
2017-04-15
2017-04-16
2017-04-17
2017-04-18
2017-04-19
2017-04-20
2017-04-21
2017-04-22
2017-04-23
2017-04-24
2017-04-25
2017-04-26
2017-04-27
2017-04-28
2017-04-29
2017-04-30
2017-05-01
2017-05-02
2017-05-03
2017-05-04
2017-05-05
2017-05-06
2017-05-07
2017-05-08
2017-05-09
2017-05-10
2017-05-11
2017-05-12
2017-05-13
2017-05-14
2017-05-15
2017-05-16
2017-05-17
2017-05-18
2017-05-19
2017-05-20
2017-05-21
2017-05-22
2017-05-23
2017-05-24
2017-05-25
2017-05-26
2017-05-27
2017-05-28
2017-05-29
2017-05-30
2017-05-31
2017-06-01
2017-06-02
2017-06-03
2017-06-04
2017-06-05
2017-06-06
2017-06-07
2017-06-08
2017-06-09
2017-06-10
2017-06-11
2017-06-12
2017-06-13
2017-06-14
2017-06-15
2017-06-16
2017-06-17
2017-06-18
2017-06-19
2017-06-20
2017-06-21
2017-06-22
2017-06-23
2017-06-24
2017-06-25
2017-06-26
2017-06-27
2017-06-28
2017-06-29
2017-06-30
2017-07-01
2017-07-02
2017-07-03
2017-07-04
2017-07-05
2017-07-06
2017-07-07
2017-07-08
2017-07-09
2017-07-10
2017-07-11
2017-07-12
2017-07-13
2017-07-14
2017-07-15
2017-07-16
2017-07-17
2017-07-18
2017-07-19
2017-07-20
2017-07-21
2017-07-22
2017-07-23
2017-07-24
2017-07-25
2017-07-26
2017-07-27
2017-07-28
2017-07-29
2017-07-30
2017-07-31
2017-08-01
2017-08-02
2017-08-03
2017-08-04
2017-08-05
2017-08-06
2017-08-07
2017-08-08
2017-08-09
2017-08-10
2017-08-11
2017-08-12
2017-08-13
2017-08-14
2017-08-15
2017-08-16
2017-08-17
2017-08-18
2017-08-19
2017-08-20
2017-08-21
2017-08-22
2017-08-23
2017-08-24
2017-08-25
2017-08-26
2017-08-27
2017-08-28
2017-08-29
2017-08-30
2017-08-31
2017-09-01
2017-09-02
2017-09-03
2017-09-04
2017-09-05
2017-09-06
2017-09-07
2017-09-08
2017-09-09
2017-09-10
2017-09-11
2017-09-12
2017-09-13
2017-09-14
2017-09-15
2017-09-16
2017-09-17
2017-09-18
2017-09-19
2017-09-20
2017-09-21
2017-09-22
2017-09-23
2017-09-24
2017-09-25
2017-09-26
2017-09-27
2017-09-28
2017-09-29
2017-09-30
2017-10-01
2017-10-02
2017-10-03
2017-10-04
2017-10-05
2017-10-06
2017-10-07
2017-10-08
2017-10-09
2017-10-10
2017-10-11
2017-10-12
2017-10-13
2017-10-14
2017-10-15
2017-10-16
2017-10-17
2017-10-18
2017-10-19
2017-10-20
2017-10-21
2017-10-22
2017-10-23
2017-10-24
2017-10-25
2017-10-26
2017-10-27
2017-10-28
2017-10-29
2017-10-30
2017-10-31
2017-11-01
2017-11-02
2017-11-03
2017-11-04
2017-11-05
2017-11-06
2017-11-07
2017-11-08
2017-11-09
2017-11-10
2017-11-11
2017-11-12
2017-11-13
2017-11-14
2017-11-15
2017-11-16
2017-11-17
2017-11-18
2017-11-19
2017-11-20
2017-11-21
2017-11-22
2017-11-23
2017-11-24
2017-11-25
2017-11-26
2017-11-27
2017-11-28
2017-11-29
2017-11-30
2017-12-01
2017-12-02
2017-12-03
2017-12-04
2017-12-05
2017-12-06
2017-12-07
2017-12-08
2017-12-09
2017-12-10
2017-12-11
2017-12-12
2017-12-13
2017-12-14
2017-12-15
2017-12-16
2017-12-17
2017-12-18
2017-12-19
2017-12-20
2017-12-21
2017-12-22
2017-12-23
2017-12-24
2017-12-25
2017-12-26
2017-12-27
2017-12-28
2017-12-29
2017-12-30
2017-12-31
2018-01-01
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-06
2018-01-07
2018-01-08
2018-01-09
2018-01-10
2018-01-11
2018-01-12
2018-01-13
2018-01-14
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-20
2018-01-21
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-27
2018-01-28
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-03
2018-02-04
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-10
2018-02-11
2018-02-12
2018-02-13
2018-02-14
2018-02-15
2018-02-16
2018-02-17
2018-02-18
2018-02-19
2018-02-20
2018-02-21
2018-02-22
2018-02-23
2018-02-24
2018-02-25
2018-02-26
2018-02-27
2018-02-28
2018-03-01
2018-03-02
2018-03-03
2018-03-04
2018-03-05
2018-03-06
2018-03-07
2018-03-08
2018-03-09
2018-03-10
2018-03-11
2018-03-12
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-17
2018-03-18
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-24
2018-03-25
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-03-31
2018-04-01
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-07
2018-04-08
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-14
2018-04-15
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-21
2018-04-22
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-28
2018-04-29
2018-04-30
2018-05-01
2018-05-02
2018-05-03
2018-05-04
2018-05-05
2018-05-06
2018-05-07
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-12
2018-05-13
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-19
2018-05-20
2018-05-21
2018-05-22
2018-05-23
2018-05-24
2018-05-25
2018-05-26
2018-05-27
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-02
2018-06-03
2018-06-04
2018-06-05
2018-06-06
2018-06-07
2018-06-08
2018-06-09
2018-06-10
2018-06-11
2018-06-12
2018-06-13
2018-06-14
2018-06-15
2018-06-16
2018-06-17
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-23
2018-06-24
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-06-30
2018-07-01
2018-07-02
2018-07-03
2018-07-04
2018-07-05
2018-07-06
2018-07-07
2018-07-08
2018-07-09
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-14
2018-07-15
2018-07-16
2018-07-17
2018-07-18
2018-07-19
2018-07-20
2018-07-21
2018-07-22
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-27
2018-07-28
2018-07-29
2018-07-30
2018-07-31
2018-08-01
2018-08-02
2018-08-03
2018-08-04
2018-08-05
2018-08-06
2018-08-07
2018-08-08
2018-08-09
2018-08-10
2018-08-11
2018-08-12
2018-08-13
2018-08-14
2018-08-15
2018-08-16
2018-08-17
2018-08-18
2018-08-19
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-24
2018-08-25
2018-08-26
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-01
2018-09-02
2018-09-03
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-08
2018-09-09
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-15
2018-09-16
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-21
2018-09-22
2018-09-23
2018-09-24
2018-09-25
2018-09-26
2018-09-27
2018-09-28
2018-09-29
2018-09-30
2018-10-01
2018-10-02
2018-10-03
2018-10-04
2018-10-05
2018-10-06
2018-10-07
2018-10-08
2018-10-09
2018-10-10
2018-10-11
2018-10-12
2018-10-13
2018-10-14
2018-10-15
2018-10-16
2018-10-17
2018-10-18
2018-10-19
2018-10-20
2018-10-21
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-27
2018-10-28
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-03
2018-11-04
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-10
2018-11-11
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-16
2018-11-17
2018-11-18
2018-11-19
2018-11-20
2018-11-21
2018-11-22
2018-11-23
2018-11-24
2018-11-25
2018-11-26
2018-11-27
2018-11-28
2018-11-29
2018-11-30
2018-12-01
2018-12-02
2018-12-03
2018-12-04
2018-12-05
2018-12-06
2018-12-07
2018-12-08
2018-12-09
2018-12-10
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-15
2018-12-16
2018-12-17
2018-12-18
2018-12-19
2018-12-20
2018-12-21
2018-12-22
2018-12-23
2018-12-24
2018-12-25
2018-12-26
2018-12-27
2018-12-28
2018-12-29
2018-12-30
2018-12-31

In [37]:
allCsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74494 entries, 0 to 74493
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      74494 non-null  object
 1   PM2.5     74494 non-null  float64
 2   PM10      74494 non-null  float64
 3   SO2       74494 non-null  float64
 4   NO2       74494 non-null  float64
 5   CO        74494 non-null  float64
 6   O3        74494 non-null  float64
 7   U(m/s)    74494 non-null  float64
 8   V(m/s)    74494 non-null  float64
 9   TEMP(K)   74494 non-null  float64
 10  RH(%)     74494 non-null  float64
 11  PSFC(Pa)  74494 non-null  float64
 12  lat       74494 non-null  float64
 13  lon       74494 non-null  float64
dtypes: float64(13), object(1)
memory usage: 8.0+ MB

In [46]:
allCsv.columns = ['date', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'U', 'V',
       'TEMP', 'RH', 'PSFC', 'lat', 'lon', 'name']

In [5]:
allCsv = pd.read_csv("PointsCapital.csv")

In [6]:
allCsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74494 entries, 0 to 74493
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    74494 non-null  object
 1   PM2.5   74494 non-null  float64
 2   PM10    74494 non-null  float64
 3   SO2     74494 non-null  float64
 4   NO2     74494 non-null  float64
 5   CO      74494 non-null  float64
 6   O3      74494 non-null  float64
 7   U       74494 non-null  float64
 8   V       74494 non-null  float64
 9   TEMP    74494 non-null  float64
 10  RH      74494 non-null  float64
 11  PSFC    74494 non-null  float64
 12  lat     74494 non-null  float64
 13  lon     74494 non-null  float64
 14  name    74494 non-null  object
dtypes: float64(13), object(2)
memory usage: 8.5+ MB

In [8]:
allCsv['WindSpeed'] = allCsv.apply(lambda col: np.sqrt(col["U"]**2+col["V"]**2), axis=1)

In [9]:
allCsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74494 entries, 0 to 74493
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       74494 non-null  object
 1   PM2.5      74494 non-null  float64
 2   PM10       74494 non-null  float64
 3   SO2        74494 non-null  float64
 4   NO2        74494 non-null  float64
 5   CO         74494 non-null  float64
 6   O3         74494 non-null  float64
 7   U          74494 non-null  float64
 8   V          74494 non-null  float64
 9   TEMP       74494 non-null  float64
 10  RH         74494 non-null  float64
 11  PSFC       74494 non-null  float64
 12  lat        74494 non-null  float64
 13  lon        74494 non-null  float64
 14  name       74494 non-null  object
 15  WindSpeed  74494 non-null  float64
dtypes: float64(14), object(2)
memory usage: 9.1+ MB

In [10]:
allCsv.head()

,date,PM2.5,PM10,SO2,NO2,CO,O3,U,V,TEMP,RH,PSFC,lat,lon,name,WindSpeed
0,2013-01-01,35.35,55.60,14.53,24.35,0.33,56.13,-4.30,-4.32,290.64,75.09,101646.27,20.02,110.31,海口,6.095277
1,2013-01-01,53.11,85.48,32.69,69.36,1.34,23.06,-0.21,-6.58,285.15,47.11,101968.33,22.12,113.32,澳门,6.583350
2,2013-01-01,56.72,93.46,17.49,70.10,1.34,13.94,-2.46,-5.45,284.00,39.27,101274.27,22.46,114.08,香港,5.979473
3,2013-01-01,98.35,111.93,52.38,58.32,1.33,22.49,-2.21,-2.30,282.83,39.36,100637.87,22.91,108.28,南宁,3.189687
4,2013-01-01,49.91,71.65,31.70,72.06,1.33,14.31,-0.68,-4.29,282.56,42.57,101818.73,23.20,113.26,广州,4.343558

In [13]:
allCsv.to_csv('Capital_Points.csv',  encoding='utf_8_sig', index=False)

In [15]:
allCsv.to_sql('Capital_Points', engine, index= False)

c:\users\colin\appdata\local\programs\python\python38\lib\site-packages\pandas\io\sql.py:1444: UserWarning: The provided table name 'Capital_Points' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)