In [1]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_csv("PointsCapital.csv")

In [14]:
data

,date,PM2.5,PM10,SO2,NO2,CO,O3,U,V,TEMP,RH,PSFC,lat,lon,name
0,2013-01-01,35.35,55.60,14.53,24.35,0.33,56.13,-4.30,-4.32,290.64,75.09,101646.27,20.02,110.31,海口
1,2013-01-01,53.11,85.48,32.69,69.36,1.34,23.06,-0.21,-6.58,285.15,47.11,101968.33,22.12,113.32,澳门
2,2013-01-01,56.72,93.46,17.49,70.10,1.34,13.94,-2.46,-5.45,284.00,39.27,101274.27,22.46,114.08,香港
3,2013-01-01,98.35,111.93,52.38,58.32,1.33,22.49,-2.21,-2.30,282.83,39.36,100637.87,22.91,108.28,南宁
4,2013-01-01,49.91,71.65,31.70,72.06,1.33,14.31,-0.68,-4.29,282.56,42.57,101818.73,23.20,113.26,广州
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74489,2018-12-31,51.44,88.37,31.03,54.09,1.90,9.96,-1.40,-1.45,260.73,63.25,89417.24,40.82,111.68,呼和浩特
74490,2018-12-31,91.07,129.21,36.10,55.81,1.81,10.93,-0.09,-3.05,260.16,36.82,103850.58,41.81,123.38,沈阳
74491,2018-12-31,24.67,39.37,1.96,27.46,0.53,45.57,-3.66,4.07,268.97,37.64,90216.61,43.71,87.67,乌鲁木齐
74492,2018-12-31,72.68,96.77,23.35,51.56,1.49,17.98,2.33,-0.95,256.44,52.61,101360.23,43.86,125.37,长春
74493,2018-12-31,62.75,81.23,40.89,47.58,1.19,26.34,3.37,-0.45,255.49,62.27,101965.32,45.71,126.66,哈尔滨

data['date'] = pd.to_datetime(data['date'])

In [15]:
data['date'][365]

'2013-01-11'

In [16]:
data['date'][365][8:]

'11'

In [17]:
data['date'].apply(lambda x: x[:4])

0        2013
1        2013
2        2013
3        2013
4        2013
         ...
74489    2018
74490    2018
74491    2018
74492    2018
74493    2018
Name: date, Length: 74494, dtype: object

In [18]:
data['year'] = data['date'].apply(lambda x: x[:4]).astype('int')
data['month'] = data['date'].apply(lambda x: x[5:7]).astype('int')
data['day'] = data['date'].apply(lambda x: x[8:]).astype('int')

In [19]:
data

,date,PM2.5,PM10,SO2,NO2,CO,O3,U,V,TEMP,RH,PSFC,lat,lon,name,year,month,day
0,2013-01-01,35.35,55.60,14.53,24.35,0.33,56.13,-4.30,-4.32,290.64,75.09,101646.27,20.02,110.31,海口,2013,1,1
1,2013-01-01,53.11,85.48,32.69,69.36,1.34,23.06,-0.21,-6.58,285.15,47.11,101968.33,22.12,113.32,澳门,2013,1,1
2,2013-01-01,56.72,93.46,17.49,70.10,1.34,13.94,-2.46,-5.45,284.00,39.27,101274.27,22.46,114.08,香港,2013,1,1
3,2013-01-01,98.35,111.93,52.38,58.32,1.33,22.49,-2.21,-2.30,282.83,39.36,100637.87,22.91,108.28,南宁,2013,1,1
4,2013-01-01,49.91,71.65,31.70,72.06,1.33,14.31,-0.68,-4.29,282.56,42.57,101818.73,23.20,113.26,广州,2013,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74489,2018-12-31,51.44,88.37,31.03,54.09,1.90,9.96,-1.40,-1.45,260.73,63.25,89417.24,40.82,111.68,呼和浩特,2018,12,31
74490,2018-12-31,91.07,129.21,36.10,55.81,1.81,10.93,-0.09,-3.05,260.16,36.82,103850.58,41.81,123.38,沈阳,2018,12,31
74491,2018-12-31,24.67,39.37,1.96,27.46,0.53,45.57,-3.66,4.07,268.97,37.64,90216.61,43.71,87.67,乌鲁木齐,2018,12,31
74492,2018-12-31,72.68,96.77,23.35,51.56,1.49,17.98,2.33,-0.95,256.44,52.61,101360.23,43.86,125.37,长春,2018,12,31
74493,2018-12-31,62.75,81.23,40.89,47.58,1.19,26.34,3.37,-0.45,255.49,62.27,101965.32,45.71,126.66,哈尔滨,2018,12,31

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74494 entries, 0 to 74493
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    74494 non-null  object
 1   PM2.5   74494 non-null  float64
 2   PM10    74494 non-null  float64
 3   SO2     74494 non-null  float64
 4   NO2     74494 non-null  float64
 5   CO      74494 non-null  float64
 6   O3      74494 non-null  float64
 7   U       74494 non-null  float64
 8   V       74494 non-null  float64
 9   TEMP    74494 non-null  float64
 10  RH      74494 non-null  float64
 11  PSFC    74494 non-null  float64
 12  lat     74494 non-null  float64
 13  lon     74494 non-null  float64
 14  name    74494 non-null  object
 15  year    74494 non-null  int32
 16  month   74494 non-null  int32
 17  day     74494 non-null  int32
dtypes: float64(13), int32(3), object(2)
memory usage: 9.4+ MB

In [21]:
data.columns

Index(['date', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'U', 'V', 'TEMP',
       'RH', 'PSFC', 'lat', 'lon', 'name', 'year', 'month', 'day'],
      dtype='object')

In [22]:
data_result = pd.pivot_table(data, index=["year", "month", "name"], 
                             values=['PM2.5', 'PM10', 'SO2', 'NO2', 
                                      'CO', 'O3', 'TEMP','RH', 'PSFC', 
                                      'lat', 'lon'], 
                             aggfunc={"PM2.5": "mean", "PM10": "mean", 
                                     "SO2": "mean", "NO2": "mean", 
                                     "CO": "mean", "O3": "mean", 
                                     "TEMP": "mean", "RH": "mean", 
                                     "PSFC": "mean",
                                     'lat': "mean", 'lon': "mean"})
data_result

                       CO        NO2         O3        PM10       PM2.5  \
year month name
2013 1     上海    1.449677  66.449355  30.580000  101.112581   90.141290
           乌鲁木齐  1.495806  35.883548  48.030323   79.128065   57.960323
           兰州    1.848387  42.590323  25.941613  107.688710   75.612903
           北京    3.981935  90.510323  11.339677  235.911290  183.109032
           南京    1.959677  72.443548  19.823871  192.855484  128.501290
...                   ...        ...        ...         ...         ...
2018 12    重庆    0.984839  44.295806   9.166452   81.740645   58.921613
           银川    1.370645  43.009032  30.750645  137.705806   49.203548
           长春    0.867097  37.631613  26.793548   64.845484   39.370968
           长沙    1.062903  41.142903  17.377097  112.090323   88.697419
           香港    0.672581  37.224194  33.190000   47.898065   30.559032

                          PSFC         RH         SO2        TEMP    lat  \
year month name
2013 1     上海    102667.284516  75.934194   32.909355  277.891290  31.20
           乌鲁木齐   89615.903871  39.700000   16.470968  268.683871  43.71
           兰州     79745.470323  40.420645   37.440323  268.185161  35.97
           北京    102456.987419  55.208710  115.113548  266.699032  39.97
           南京    102544.700323  61.958387   70.261613  276.170645  32.09
...                        ...        ...         ...         ...    ...
2018 12    重庆     99178.401290  61.665161   33.239677  282.026452  29.57
           银川     89903.558387  37.227419   41.630645  267.567742  38.41
           长春    100005.130000  45.749355   24.990968  262.734516  43.86
           长沙    102197.059677  74.754194   19.595484  280.453226  28.23
           香港    101303.623226  72.902903   11.332581  289.591290  22.46

                    lon
year month name
2013 1     上海    121.53
           乌鲁木齐   87.67
           兰州    103.74
           北京    116.38
           南京    118.77
...                 ...
2018 12    重庆    106.48
           银川    106.30
           长春    125.37
           长沙    112.94
           香港    114.08

[2448 rows x 11 columns]

In [23]:
data_result.index

MultiIndex([(2013,  1,   '上海'),
            (2013,  1, '乌鲁木齐'),
            (2013,  1,   '兰州'),
            (2013,  1,   '北京'),
            (2013,  1,   '南京'),
            (2013,  1,   '南宁'),
            (2013,  1,   '南昌'),
            (2013,  1,   '台北'),
            (2013,  1,   '合肥'),
            (2013,  1, '呼和浩特'),
            ...
            (2018, 12,   '福州'),
            (2018, 12,   '西宁'),
            (2018, 12,   '西安'),
            (2018, 12,   '贵阳'),
            (2018, 12,   '郑州'),
            (2018, 12,   '重庆'),
            (2018, 12,   '银川'),
            (2018, 12,   '长春'),
            (2018, 12,   '长沙'),
            (2018, 12,   '香港')],
           names=['year', 'month', 'name'], length=2448)

In [24]:
list(pd.unique(data['name']))

['海口',
 '澳门',
 '香港',
 '南宁',
 '广州',
 '昆明',
 '台北',
 '贵阳',
 '福州',
 '长沙',
 '南昌',
 '重庆',
 '成都',
 '拉萨',
 '武汉',
 '杭州',
 '上海',
 '合肥',
 '南京',
 '西安',
 '郑州',
 '兰州',
 '西宁',
 '济南',
 '太原',
 '银川',
 '石家庄',
 '天津',
 '北京',
 '呼和浩特',
 '沈阳',
 '乌鲁木齐',
 '长春',
 '哈尔滨']

In [25]:
data_result.describe()

,CO,NO2,O3,PM10,PM2.5,PSFC,RH,SO2,TEMP,lat,lon
count,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000,2448.000000
mean,1.047989,40.264256,51.831303,88.011666,51.274569,95497.825206,59.943704,23.812500,288.143554,32.479118,112.313824
std,0.560417,17.063942,22.801730,50.936312,32.911534,9583.400042,16.218389,26.465653,10.707732,6.914948,8.533308
min,0.102903,1.182857,7.371333,7.168929,2.761429,57562.202500,20.778000,0.070667,247.523226,20.020000,87.670000
25%,0.730567,29.077661,34.316452,52.915806,28.951774,90852.094250,46.019113,9.992339,281.039118,26.580000,106.740000
50%,0.958641,40.104113,50.936280,78.303500,43.655405,99850.103871,61.410645,15.640952,290.164500,31.515000,113.510000
75%,1.238854,51.699712,67.151935,114.598548,64.659514,101202.516000,73.987097,25.822750,296.690500,38.070000,117.280000
max,5.509032,103.549032,150.737667,551.080645,301.158387,103190.929032,93.729667,259.926774,304.450968,45.710000,126.660000

In [12]:
# data_result[('2013-01-01','上海')]
# location = ['上海', '北京']
location = list(pd.unique(data['name']))
year = [2018]
filter_result = data_result.query('year ==  '+str(year)+' and name == '+str(location))
filter_result

                       CO        NO2         O3        PM10      PM2.5  \
year month name
2018 1     上海    0.926452  57.413226  38.519677   75.039355  56.714516
           乌鲁木齐  1.075161  49.810000  38.876129   87.804516  58.876129
           兰州    1.668065  51.886774  37.779032  117.082903  59.921613
           北京    0.862581  47.897742  28.804839   63.901290  33.813871
           南京    1.108387  60.366774  31.984839  123.376774  89.807097
...                   ...        ...        ...         ...        ...
     12    重庆    0.984839  44.295806   9.166452   81.740645  58.921613
           银川    1.370645  43.009032  30.750645  137.705806  49.203548
           长春    0.867097  37.631613  26.793548   64.845484  39.370968
           长沙    1.062903  41.142903  17.377097  112.090323  88.697419
           香港    0.672581  37.224194  33.190000   47.898065  30.559032

                          PSFC         RH        SO2        TEMP    lat  \
year month name
2018 1     上海    102540.384516  72.939355  13.300323  278.428710  31.20
           乌鲁木齐   89971.483226  55.081935   5.788387  261.868710  43.71
           兰州     79606.077419  56.944839  28.705484  266.719032  35.97
           北京    102381.320968  32.786774   9.053226  269.558710  39.97
           南京    102473.774516  67.554516  15.451290  275.326129  32.09
...                        ...        ...        ...         ...    ...
     12    重庆     99178.401290  61.665161  33.239677  282.026452  29.57
           银川     89903.558387  37.227419  41.630645  267.567742  38.41
           长春    100005.130000  45.749355  24.990968  262.734516  43.86
           长沙    102197.059677  74.754194  19.595484  280.453226  28.23
           香港    101303.623226  72.902903  11.332581  289.591290  22.46

                    lon
year month name
2018 1     上海    121.53
           乌鲁木齐   87.67
           兰州    103.74
           北京    116.38
           南京    118.77
...                 ...
     12    重庆    106.48
           银川    106.30
           长春    125.37
           长沙    112.94
           香港    114.08

[408 rows x 11 columns]

In [104]:
12*34

408

In [13]:
filter_result.reset_index()

,year,month,name,CO,NO2,O3,PM10,PM2.5,PSFC,RH,SO2,TEMP,lat,lon
0,2018,1,上海,0.926452,57.413226,38.519677,75.039355,56.714516,102540.384516,72.939355,13.300323,278.428710,31.20,121.53
1,2018,1,乌鲁木齐,1.075161,49.810000,38.876129,87.804516,58.876129,89971.483226,55.081935,5.788387,261.868710,43.71,87.67
2,2018,1,兰州,1.668065,51.886774,37.779032,117.082903,59.921613,79606.077419,56.944839,28.705484,266.719032,35.97,103.74
3,2018,1,北京,0.862581,47.897742,28.804839,63.901290,33.813871,102381.320968,32.786774,9.053226,269.558710,39.97,116.38
4,2018,1,南京,1.108387,60.366774,31.984839,123.376774,89.807097,102473.774516,67.554516,15.451290,275.326129,32.09,118.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2018,12,重庆,0.984839,44.295806,9.166452,81.740645,58.921613,99178.401290,61.665161,33.239677,282.026452,29.57,106.48
404,2018,12,银川,1.370645,43.009032,30.750645,137.705806,49.203548,89903.558387,37.227419,41.630645,267.567742,38.41,106.30
405,2018,12,长春,0.867097,37.631613,26.793548,64.845484,39.370968,100005.130000,45.749355,24.990968,262.734516,43.86,125.37
406,2018,12,长沙,1.062903,41.142903,17.377097,112.090323,88.697419,102197.059677,74.754194,19.595484,280.453226,28.23,112.94
407,2018,12,香港,0.672581,37.224194,33.190000,47.898065,30.559032,101303.623226,72.902903,11.332581,289.591290,22.46,114.08

In [14]:
year_result = pd.pivot_table(filter_result.reset_index(), index=["year", "name"], 
                             values=['PM2.5', 'PM10', 'SO2', 'NO2', 
                                      'CO', 'O3', 'TEMP','RH', 'PSFC', 
                                      'lat', 'lon'], 
                             aggfunc={"PM2.5": "mean", "PM10": "mean", 
                                     "SO2": "mean", "NO2": "mean", 
                                     "CO": "mean", "O3": "mean", 
                                     "TEMP": "mean", "RH": "mean", 
                                     "PSFC": "mean",
                                     'lat': "mean", 'lon': "mean"})
year_result

                 CO        NO2         O3        PM10      PM2.5  \
year name
2018 上海    0.620760  39.895579  66.469001   52.633629  34.524188
     乌鲁木齐  0.522078  25.796500  63.722618   53.288490  29.023759
     兰州    0.876270  33.755147  61.364391   91.643747  39.842967
     北京    0.857584  45.291660  55.122219   85.419765  51.327542
     南京    0.815374  44.190297  58.585519   78.406973  44.546177
     南宁    1.042967  39.063793  44.142781   60.846818  35.087343
     南昌    0.974398  32.204763  55.242873   62.798826  30.200042
     台北    0.208649  16.429101  65.229526   24.848132  19.243179
     合肥    0.839720  40.599743  63.818099   77.486582  47.970269
     呼和浩特  1.060933  36.453294  57.926501   86.176052  34.909152
     哈尔滨   0.776574  37.205154  53.495683   62.720765  37.377328
     天津    1.104634  47.090532  60.229479   95.793025  55.549789
     太原    1.049669  48.916398  56.201637  124.001891  53.625686
     广州    0.839029  49.106640  47.035264   58.613410  35.769873
     成都    0.900537  51.660500  46.168747   84.375491  50.842707
     拉萨    0.202607   4.240054  89.507985   14.281125   7.764472
     昆明    0.866441  35.184147  50.288277   53.754835  28.162260
     杭州    0.847634  40.503392  55.671819   65.569362  39.022242
     武汉    1.027604  46.626498  49.345337   79.196828  48.123840
     沈阳    1.046160  42.116279  54.497035   76.228071  40.461202
     济南    0.924606  43.581312  74.812486  109.159844  52.629740
     海口    0.479490  10.801788  54.278410   31.678525  18.071075
     澳门    0.439842  18.564343  66.741745   34.679642  22.988874
     石家庄   1.182237  47.290023  62.235337  134.336586  71.868604
     福州    0.695929  27.888666  59.265679   47.725004  25.453389
     西宁    1.330799  29.849528  62.098713   90.069309  41.435934
     西安    1.219440  54.612163  52.436754  120.954608  61.493443
     贵阳    0.598349  20.873670  53.591084   51.357611  30.663973
     郑州    1.062690  43.661619  66.904755  114.292083  63.237137
     重庆    0.899829  43.273987  41.201241   62.804267  38.200135
     银川    0.896310  36.787293  67.413951  116.964397  41.376681
     长春    0.878490  38.030895  50.605519   64.897498  33.241953
     长沙    0.890691  33.404695  57.278601   71.716214  46.628011
     香港    0.475225  26.499511  58.686634   36.018432  23.248171

                    PSFC         RH        SO2        TEMP    lat     lon
year name
2018 上海    101609.629443  76.779278  10.449371  290.218997  31.20  121.53
     乌鲁木齐   89476.656977  41.941816   4.638785  281.371784  43.71   87.67
     兰州     79717.316134  50.285362  14.658722  281.463997  35.97  103.74
     北京    101278.768108  39.358575   7.189376  286.883918  39.97  116.38
     南京    101438.873326  64.405512  11.691891  290.191301  32.09  118.77
     南宁     99776.062144  68.547848  13.912006  295.394647  22.91  108.28
     南昌    101320.700957  67.066322  12.208501  292.557573  28.68  115.93
     台北     98976.126301  77.093249  10.711136  294.921716  25.03  121.52
     合肥    101439.119397  61.926558   8.560085  290.614012  31.83  117.28
     呼和浩特   88316.297387  43.851249  18.723860  280.818593  40.82  111.68
     哈尔滨    99587.794808  59.103863  19.336504  277.914138  45.71  126.66
     天津    101746.880989  44.478184  14.357367  286.738158  39.09  117.13
     太原     90795.683630  43.738109  27.889757  284.075441  37.93  112.48
     广州    100962.780694  69.133380  11.060386  296.028348  23.20  113.26
     成都     95394.339418  62.664778  11.318555  290.327148  30.66  104.13
     拉萨     58068.095848  50.245044   1.072357  274.059175  30.01   91.07
     昆明     80113.239233  72.893802  14.434166  287.440096  25.08  102.69
     杭州    101593.993245  72.200148   9.722956  290.739283  30.27  120.24
     武汉    101440.548287  60.010560  11.832413  291.691215  30.59  114.25
     沈阳    101269.728572  50.790368  26.107971  282.439169  41.81  123.38
     济南    100979.454084  45.288337  17.180689  288.746663  36.65  116.95
     海口    100887.768189  80.045241   7.026381  297.640272  20.02  110.31
     澳门    101156.521040  78.862959   7.346567  296.124149  22.12  113.32
     石家庄   101141.128902  39.276657  22.969321  288.273236  38.07  114.56
     福州     98789.373426  76.155897   9.800142  292.520982  26.14  119.28
     西宁     75751.535017  51.254569  15.155591  279.178523  36.61  101.70
     西安     97328.193379  44.806908  15.311292  289.925730  34.28  108.87
     贵阳     88394.874224  77.791151  11.016892  287.668925  26.58  106.74
     郑州    100334.886232  46.024081  15.067638  289.474373  34.73  113.70
     重庆     98080.396575  62.551978  11.802231  292.652665  29.57  106.48
     银川     89086.176592  38.394769  30.209665  284.860888  38.41  106.30
     长春     98984.429491  55.982404  16.568525  279.497245  43.86  125.37
     长沙    100971.134964  67.123751  10.916762  292.010102  28.23  112.94
     香港    100513.310537  77.860696   7.316495  295.546514  22.46  114.08

In [27]:
res = year_result.reset_index()
res

,year,name,CO,NO2,O3,PM10,PM2.5,PSFC,RH,SO2,TEMP,lat,lon
0,2018,上海,0.620760,39.895579,66.469001,52.633629,34.524188,101609.629443,76.779278,10.449371,290.218997,31.20,121.53
1,2018,乌鲁木齐,0.522078,25.796500,63.722618,53.288490,29.023759,89476.656977,41.941816,4.638785,281.371784,43.71,87.67
2,2018,兰州,0.876270,33.755147,61.364391,91.643747,39.842967,79717.316134,50.285362,14.658722,281.463997,35.97,103.74
3,2018,北京,0.857584,45.291660,55.122219,85.419765,51.327542,101278.768108,39.358575,7.189376,286.883918,39.97,116.38
4,2018,南京,0.815374,44.190297,58.585519,78.406973,44.546177,101438.873326,64.405512,11.691891,290.191301,32.09,118.77
5,2018,南宁,1.042967,39.063793,44.142781,60.846818,35.087343,99776.062144,68.547848,13.912006,295.394647,22.91,108.28
6,2018,南昌,0.974398,32.204763,55.242873,62.798826,30.200042,101320.700957,67.066322,12.208501,292.557573,28.68,115.93
7,2018,台北,0.208649,16.429101,65.229526,24.848132,19.243179,98976.126301,77.093249,10.711136,294.921716,25.03,121.52
8,2018,合肥,0.839720,40.599743,63.818099,77.486582,47.970269,101439.119397,61.926558,8.560085,290.614012,31.83,117.28
9,2018,呼和浩特,1.060933,36.453294,57.926501,86.176052,34.909152,88316.297387,43.851249,18.723860,280.818593,40.82,111.68
10,2018,哈尔滨,0.776574,37.205154,53.495683,62.720765,37.377328,99587.794808,59.103863,19.336504,277.914138,45.71,126.66
11,2018,天津,1.104634,47.090532,60.229479,95.793025,55.549789,101746.880989,44.478184,14.357367,286.738158,39.09,117.13
12,2018,太原,1.049669,48.916398,56.201637,124.001891,53.625686,90795.683630,43.738109,27.889757,284.075441,37.93,112.48
13,2018,广州,0.839029,49.106640,47.035264,58.613410,35.769873,100962.780694,69.133380,11.060386,296.028348,23.20,113.26
14,2018,成都,0.900537,51.660500,46.168747,84.375491,50.842707,95394.339418,62.664778,11.318555,290.327148,30.66,104.13
15,2018,拉萨,0.202607,4.240054,89.507985,14.281125,7.764472,58068.095848,50.245044,1.072357,274.059175,30.01,91.07
16,2018,昆明,0.866441,35.184147,50.288277,53.754835,28.162260,80113.239233,72.893802,14.434166,287.440096,25.08,102.69
17,2018,杭州,0.847634,40.503392,55.671819,65.569362,39.022242,101593.993245,72.200148,9.722956,290.739283,30.27,120.24
18,2018,武汉,1.027604,46.626498,49.345337,79.196828,48.123840,101440.548287,60.010560,11.832413,291.691215,30.59,114.25
19,2018,沈阳,1.046160,42.116279,54.497035,76.228071,40.461202,101269.728572,50.790368,26.107971,282.439169,41.81,123.38
20,2018,济南,0.924606,43.581312,74.812486,109.159844,52.629740,100979.454084,45.288337,17.180689,288.746663,36.65,116.95
21,2018,海口,0.479490,10.801788,54.278410,31.678525,18.071075,100887.768189,80.045241,7.026381,297.640272,20.02,110.31
22,2018,澳门,0.439842,18.564343,66.741745,34.679642,22.988874,101156.521040,78.862959,7.346567,296.124149,22.12,113.32
23,2018,石家庄,1.182237,47.290023,62.235337,134.336586,71.868604,101141.128902,39.276657,22.969321,288.273236,38.07,114.56
24,2018,福州,0.695929,27.888666,59.265679,47.725004,25.453389,98789.373426,76.155897,9.800142,292.520982,26.14,119.28
25,2018,西宁,1.330799,29.849528,62.098713,90.069309,41.435934,75751.535017,51.254569,15.155591,279.178523,36.61,101.70
26,2018,西安,1.219440,54.612163,52.436754,120.954608,61.493443,97328.193379,44.806908,15.311292,289.925730,34.28,108.87
27,2018,贵阳,0.598349,20.873670,53.591084,51.357611,30.663973,88394.874224,77.791151,11.016892,287.668925,26.58,106.74
28,2018,郑州,1.062690,43.661619,66.904755,114.292083,63.237137,100334.886232,46.024081,15.067638,289.474373,34.73,113.70
29,2018,重庆,0.899829,43.273987,41.201241,62.804267,38.200135,98080.396575,62.551978,11.802231,292.652665,29.57,106.48
30,2018,银川,0.896310,36.787293,67.413951,116.964397,41.376681,89086.176592,38.394769,30.209665,284.860888,38.41,106.30
31,2018,长春,0.878490,38.030895,50.605519,64.897498,33.241953,98984.429491,55.982404,16.568525,279.497245,43.86,125.37
32,2018,长沙,0.890691,33.404695,57.278601,71.716214,46.628011,100971.134964,67.123751,10.916762,292.010102,28.23,112.94
33,2018,香港,0.475225,26.499511,58.686634,36.018432,23.248171,100513.310537,77.860696,7.316495,295.546514,22.46,114.08

In [21]:
res.columns

Index(['year', 'name', 'CO', 'NO2', 'O3', 'PM10', 'PM2.5', 'PSFC', 'RH', 'SO2',
       'TEMP', 'lat', 'lon'],
      dtype='object')

In [28]:
res[['CO', 'NO2', 'O3', 'PM10', 'PM2.5', 'PSFC', 'RH', 'SO2','TEMP']] = res[['CO', 'NO2', 'O3', 'PM10', 'PM2.5', 'PSFC', 'RH', 'SO2','TEMP']].apply(lambda x: (x - np.min(x)) / (np.max(x) - np.min(x)))

In [29]:
res

,year,name,CO,NO2,O3,PM10,PM2.5,PSFC,RH,SO2,TEMP,lat,lon
0,2018,上海,0.370640,0.707843,0.523069,0.319457,0.417441,0.996858,0.921586,0.321822,0.685287,31.20,121.53
1,2018,乌鲁木齐,0.283171,0.427944,0.466216,0.324911,0.331637,0.719080,0.085162,0.122401,0.310105,43.71,87.67
2,2018,兰州,0.597118,0.585941,0.417398,0.644391,0.500412,0.495646,0.285485,0.466288,0.314015,35.97,103.74
3,2018,北京,0.580555,0.814967,0.288179,0.592548,0.679567,0.989283,0.023140,0.209938,0.543857,39.97,116.38
4,2018,南京,0.543141,0.793102,0.359873,0.534135,0.573781,0.992948,0.624501,0.364465,0.684113,32.09,118.77
5,2018,南宁,0.744874,0.691330,0.060893,0.387868,0.426226,0.954879,0.723955,0.440660,0.904770,22.91,108.28
6,2018,南昌,0.684095,0.555163,0.290676,0.404127,0.349986,0.990243,0.688385,0.382195,0.784459,28.68,115.93
7,2018,台北,0.005355,0.241980,0.497411,0.088018,0.179063,0.936565,0.929125,0.330805,0.884715,25.03,121.52
8,2018,合肥,0.564720,0.721822,0.468193,0.526469,0.627195,0.992954,0.564983,0.256981,0.702038,31.83,117.28
9,2018,呼和浩特,0.760798,0.639505,0.346230,0.598848,0.423447,0.692515,0.131006,0.605804,0.286646,40.82,111.68
10,2018,哈尔滨,0.508750,0.654432,0.254508,0.403477,0.461949,0.950569,0.497212,0.626830,0.163477,45.71,126.66
11,2018,天津,0.799533,0.850679,0.393904,0.678952,0.745433,1.000000,0.146059,0.455945,0.537676,39.09,117.13
12,2018,太原,0.750814,0.886926,0.310524,0.913917,0.715417,0.749279,0.128290,0.920380,0.424758,37.93,112.48
13,2018,广州,0.564108,0.890703,0.120770,0.369265,0.436874,0.982048,0.738014,0.342792,0.931643,23.20,113.26
14,2018,成都,0.618627,0.941403,0.102833,0.583850,0.672004,0.854562,0.582707,0.351652,0.689873,30.66,104.13
15,2018,拉萨,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.284517,0.000000,0.000000,30.01,91.07
16,2018,昆明,0.588406,0.614310,0.188111,0.328796,0.318198,0.504711,0.828299,0.458581,0.567443,25.08,102.69
17,2018,杭州,0.571736,0.719909,0.299556,0.427205,0.487609,0.996500,0.811645,0.296891,0.707351,30.27,120.24
18,2018,武汉,0.731256,0.841467,0.168591,0.540714,0.629591,0.992987,0.518981,0.369288,0.747719,30.59,114.25
19,2018,沈阳,0.747703,0.751929,0.275237,0.515986,0.510057,0.989076,0.297610,0.859229,0.355369,41.81,123.38
20,2018,济南,0.639961,0.781013,0.695788,0.790291,0.699881,0.982430,0.165510,0.552842,0.622850,36.65,116.95
21,2018,海口,0.245422,0.130265,0.270711,0.144911,0.160779,0.980331,1.000000,0.204344,1.000000,20.02,110.31
22,2018,澳门,0.210279,0.284369,0.528715,0.169909,0.237495,0.986484,0.971614,0.215333,0.935706,22.12,113.32
23,2018,石家庄,0.868319,0.854639,0.435428,1.000000,1.000000,0.986132,0.021174,0.751510,0.602774,38.07,114.56
24,2018,福州,0.437268,0.469478,0.373953,0.278570,0.275940,0.932290,0.906619,0.299540,0.782907,26.14,119.28
25,2018,西宁,1.000000,0.508406,0.432599,0.631276,0.525262,0.404852,0.308755,0.483340,0.217095,36.61,101.70
26,2018,西安,0.901294,1.000000,0.232587,0.888535,0.838151,0.898837,0.153951,0.488684,0.672851,34.28,108.87
27,2018,贵阳,0.350776,0.330215,0.256483,0.308828,0.357223,0.694314,0.945881,0.341299,0.577147,26.58,106.74
28,2018,郑州,0.762356,0.782607,0.532090,0.833040,0.865352,0.967673,0.183175,0.480322,0.653710,34.73,113.70
29,2018,重庆,0.617999,0.774912,0.000000,0.404173,0.474785,0.916058,0.579998,0.368252,0.788491,29.57,106.48
30,2018,银川,0.614880,0.646136,0.542630,0.855299,0.524338,0.710141,0.000000,1.000000,0.458067,38.41,106.30
31,2018,长春,0.599085,0.670824,0.194678,0.421608,0.397439,0.936755,0.422267,0.531833,0.230611,43.86,125.37
32,2018,长沙,0.609900,0.578984,0.332818,0.478405,0.606256,0.982240,0.689764,0.337863,0.761242,28.23,112.94
33,2018,香港,0.241642,0.441900,0.361966,0.181061,0.241540,0.971758,0.947551,0.214300,0.911210,22.46,114.08

In [30]:
jd = res.to_json(orient="records", force_ascii=False)
jd

'[{"year":2018,"name":"上海","CO":0.3706397969,"NO2":0.7078426127,"O3":0.5230689973,"PM10":0.3194565538,"PM2.5":0.4174413606,"PSFC":0.9968577069,"RH":0.9215864085,"SO2":0.3218215916,"TEMP":0.6852871415,"lat":31.2,"lon":121.53},{"year":2018,"name":"乌鲁木齐","CO":0.2831714234,"NO2":0.4279440898,"O3":0.4662159962,"PM10":0.3249112082,"PM2.5":0.331636761,"PSFC":0.719080465,"RH":0.0851622284,"SO2":0.1224007653,"TEMP":0.3101047264,"lat":43.71,"lon":87.67},{"year":2018,"name":"兰州","CO":0.5971175604,"NO2":0.5859411843,"O3":0.4173982302,"PM10":0.6443906905,"PM2.5":0.5004122871,"PSFC":0.4956461178,"RH":0.2854852068,"SO2":0.4662876021,"TEMP":0.3140151893,"lat":35.97,"lon":103.74},{"year":2018,"name":"北京","CO":0.5805548392,"NO2":0.8149669784,"O3":0.2881787545,"PM10":0.592548137,"PM2.5":0.6795672756,"PSFC":0.9892828319,"RH":0.0231403352,"SO2":0.2099376818,"TEMP":0.5438569304,"lat":39.97,"lon":116.38},{"year":2018,"name":"南京","CO":0.5431411151,"NO2":0.7931024355,"O3":0.3598726771,"PM10":0.5341352037,"PM2.5":0.5737805651,"PSFC":0.9929483464,"RH":0.6245005576,"SO2":0.364465176,"TEMP":0.6841126314,"lat":32.09,"lon":118.77},{"year":2018,"name":"南宁","CO":0.7448737082,"NO2":0.6913297685,"O3":0.060892944,"PM10":0.3878681819,"PM2.5":0.4262263701,"PSFC":0.954879266,"RH":0.7239552875,"SO2":0.4406600922,"TEMP":0.9047701143,"lat":22.91,"lon":108.28},{"year":2018,"name":"南昌","CO":0.6840954329,"NO2":0.5551625568,"O3":0.2906764207,"PM10":0.4041273962,"PM2.5":0.3499863345,"PSFC":0.9902428597,"RH":0.6883848383,"SO2":0.3821953686,"TEMP":0.7844587496,"lat":28.68,"lon":115.93},{"year":2018,"name":"台北","CO":0.0053554589,"NO2":0.2419800807,"O3":0.4974105617,"PM10":0.0880177152,"PM2.5":0.1790634456,"PSFC":0.9365652071,"RH":0.9291246549,"SO2":0.3308054183,"TEMP":0.8847146094,"lat":25.03,"lon":121.52},{"year":2018,"name":"合肥","CO":0.5647202675,"NO2":0.721821842,"O3":0.468192555,"PM10":0.5264688214,"PM2.5":0.6271950988,"PSFC":0.99295398,"RH":0.564982547,"SO2":0.2569807967,"TEMP":0.7020384706,"lat":31.83,"lon":117.28},{"year":2018,"name":"呼和浩特","CO":0.760798483,"NO2":0.6395054796,"O3":0.3462303279,"PM10":0.5988476182,"PM2.5":0.4234466556,"PSFC":0.6925147172,"RH":0.1310064465,"SO2":0.6058041847,"TEMP":0.2866456404,"lat":40.82,"lon":111.68},{"year":2018,"name":"哈尔滨","CO":0.5087495945,"NO2":0.6544315981,"O3":0.2545077684,"PM10":0.4034771885,"PM2.5":0.4619492629,"PSFC":0.9505689965,"RH":0.4972115206,"SO2":0.6268302931,"TEMP":0.1634768266,"lat":45.71,"lon":126.66},{"year":2018,"name":"天津","CO":0.7995333716,"NO2":0.8506786487,"O3":0.3939043733,"PM10":0.6789520334,"PM2.5":0.7454327112,"PSFC":1.0,"RH":0.146058741,"SO2":0.455945019,"TEMP":0.5376757117,"lat":39.09,"lon":117.13},{"year":2018,"name":"太原","CO":0.7508138993,"NO2":0.8869262155,"O3":0.3105238492,"PM10":0.9139173235,"PM2.5":0.7154174496,"PSFC":0.7492788015,"RH":0.1282900328,"SO2":0.9203801639,"TEMP":0.4247583,"lat":37.93,"lon":112.48},{"year":2018,"name":"广州","CO":0.5641080772,"NO2":0.8907029407,"O3":0.1207703669,"PM10":0.3692650404,"PM2.5":0.436873572,"PSFC":0.9820484866,"RH":0.7380135104,"SO2":0.3427917824,"TEMP":0.931643375,"lat":23.2,"lon":113.26},{"year":2018,"name":"成都","CO":0.6186268195,"NO2":0.9414028289,"O3":0.1028325446,"PM10":0.5838498781,"PM2.5":0.6720040296,"PSFC":0.854562311,"RH":0.5827066972,"SO2":0.3516522108,"TEMP":0.6898734649,"lat":30.66,"lon":104.13},{"year":2018,"name":"拉萨","CO":0.0,"NO2":0.0,"O3":1.0,"PM10":0.0,"PM2.5":0.0,"PSFC":0.0,"RH":0.2845171823,"SO2":0.0,"TEMP":0.0,"lat":30.01,"lon":91.07},{"year":2018,"name":"昆明","CO":0.5884056924,"NO2":0.6143100562,"O3":0.1881111135,"PM10":0.3287956254,"PM2.5":0.3181977166,"PSFC":0.5047105434,"RH":0.828298727,"SO2":0.4585807596,"TEMP":0.5674426806,"lat":25.08,"lon":102.69},{"year":2018,"name":"杭州","CO":0.5717356918,"NO2":0.7199090624,"O3":0.2995560619,"PM10":0.4272045313,"PM2.5":0.4876092886,"PSFC":0.9964997254,"RH":0.8116445718,"SO2":0.2968908397,"TEMP":0.7073508321,"lat":30.27,"lon":120.24},{"year":2018,"name":"武汉","CO":0.7312559221,"NO2":0.8414665185,"O3":0.1685912898,"PM10":0.5407142883,"PM2.5":0.6295907445,"PSFC":0.9929866936,"RH":0.5189807085,"SO2":0.3692879414,"TEMP":0.7477192361,"lat":30.59,"lon":114.25},{"year":2018,"name":"沈阳","CO":0.7477034782,"NO2":0.7519285118,"O3":0.2752368078,"PM10":0.515986073,"PM2.5":0.5100565177,"PSFC":0.9890758771,"RH":0.297610047,"SO2":0.8592287905,"TEMP":0.3553691373,"lat":41.81,"lon":123.38},{"year":2018,"name":"济南","CO":0.6399611752,"NO2":0.7810127219,"O3":0.6957878318,"PM10":0.7902907342,"PM2.5":0.6998810672,"PSFC":0.9824302141,"RH":0.1655099726,"SO2":0.5528421626,"TEMP":0.6228500771,"lat":36.65,"lon":116.95},{"year":2018,"name":"海口","CO":0.2454224725,"NO2":0.1302652317,"O3":0.2707110423,"PM10":0.1449113627,"PM2.5":0.1607790782,"PSFC":0.9803311196,"RH":1.0,"SO2":0.2043436814,"TEMP":1.0,"lat":20.02,"lon":110.31},{"year":2018,"name":"澳门","CO":0.2102794857,"NO2":0.2843694531,"O3":0.528715077,"PM10":0.169909117,"PM2.5":0.2374948692,"PSFC":0.9864840575,"RH":0.9716142128,"SO2":0.2153325174,"TEMP":0.9357060129,"lat":22.12,"lon":113.32},{"year":2018,"name":"石家庄","CO":0.8683190224,"NO2":0.8546389894,"O3":0.4354277364,"PM10":1.0,"PM2.5":1.0,"PSFC":0.9861316636,"RH":0.0211735462,"SO2":0.7515095093,"TEMP":0.6027735452,"lat":38.07,"lon":114.56},{"year":2018,"name":"福州","CO":0.4372681736,"NO2":0.4694782892,"O3":0.3739527094,"PM10":0.2785702407,"PM2.5":0.2759403547,"PSFC":0.9322896103,"RH":0.9066194698,"SO2":0.2995398722,"TEMP":0.7829070726,"lat":26.14,"lon":119.28},{"year":2018,"name":"西宁","CO":1.0,"NO2":0.5084058229,"O3":0.432599471,"PM10":0.6312764389,"PM2.5":0.5252619553,"PSFC":0.4048519003,"RH":0.3087552084,"SO2":0.4833402727,"TEMP":0.2170954136,"lat":36.61,"lon":101.7},{"year":2018,"name":"西安","CO":0.9012942964,"NO2":1.0,"O3":0.2325868384,"PM10":0.88853503,"PM2.5":0.8381514563,"PSFC":0.8988367557,"RH":0.153951165,"SO2":0.4886839662,"TEMP":0.672850606,"lat":34.28,"lon":108.87},{"year":2018,"name":"贵阳","CO":0.3507758664,"NO2":0.330214813,"O3":0.2564826644,"PM10":0.3088279872,"PM2.5":0.3572234762,"PSFC":0.6943136875,"RH":0.9458808052,"SO2":0.3412990443,"TEMP":0.5771465991,"lat":26.58,"lon":106.74},{"year":2018,"name":"郑州","CO":0.762355821,"NO2":0.7826069937,"O3":0.5320895444,"PM10":0.833039638,"PM2.5":0.8653524086,"PSFC":0.9676732136,"RH":0.1831746772,"SO2":0.4803217043,"TEMP":0.6537099723,"lat":34.73,"lon":113.7},{"year":2018,"name":"重庆","CO":0.6179994252,"NO2":0.7749116208,"O3":0.0,"PM10":0.4041727137,"PM2.5":0.4747847317,"PSFC":0.9160580038,"RH":0.5799984464,"SO2":0.3682520732,"TEMP":0.7884913168,"lat":29.57,"lon":106.48},{"year":2018,"name":"银川","CO":0.6148800973,"NO2":0.6461361215,"O3":0.5426304457,"PM10":0.85529863,"PM2.5":0.524337637,"PSFC":0.7101406471,"RH":0.0,"SO2":1.0,"TEMP":0.4580666099,"lat":38.41,"lon":106.3},{"year":2018,"name":"长春","CO":0.5990850108,"NO2":0.6708244203,"O3":0.1946783525,"PM10":0.4216082544,"PM2.5":0.3974389863,"PSFC":0.9367553038,"RH":0.422267379,"SO2":0.5318325444,"TEMP":0.2306114346,"lat":43.86,"lon":125.37},{"year":2018,"name":"长沙","CO":0.6098999743,"NO2":0.5789839141,"O3":0.3328181136,"PM10":0.4784046334,"PM2.5":0.606256385,"PSFC":0.9822397527,"RH":0.6897636645,"SO2":0.337862557,"TEMP":0.7612422409,"lat":28.23,"lon":112.94},{"year":2018,"name":"香港","CO":0.2416415979,"NO2":0.4419004364,"O3":0.3619658806,"PM10":0.1810605459,"PM2.5":0.2415397981,"PSFC":0.9717581327,"RH":0.9475505479,"SO2":0.2143004515,"TEMP":0.9112103178,"lat":22.46,"lon":114.08}]'

In [31]:
fh = open('2018CapitalMean.json', 'w', encoding='utf-8')
fh.write(jd)
fh.close()

In [2]:
import json

In [6]:
fh = open('2018CapitalMean.json', 'r', encoding='utf-8')
jd = fh.readlines()
fh.close()

In [13]:
jd = json.loads(jd[0])

In [14]:
jd

[{'year': 2018,
  'name': '上海',
  'CO': 0.3706397969,
  'NO2': 0.7078426127,
  'O3': 0.5230689973,
  'PM10': 0.3194565538,
  'PM2.5': 0.4174413606,
  'PSFC': 0.9968577069,
  'RH': 0.9215864085,
  'SO2': 0.3218215916,
  'TEMP': 0.6852871415,
  'lat': 31.2,
  'lon': 121.53},
 {'year': 2018,
  'name': '乌鲁木齐',
  'CO': 0.2831714234,
  'NO2': 0.4279440898,
  'O3': 0.4662159962,
  'PM10': 0.3249112082,
  'PM2.5': 0.331636761,
  'PSFC': 0.719080465,
  'RH': 0.0851622284,
  'SO2': 0.1224007653,
  'TEMP': 0.3101047264,
  'lat': 43.71,
  'lon': 87.67},
 {'year': 2018,
  'name': '兰州',
  'CO': 0.5971175604,
  'NO2': 0.5859411843,
  'O3': 0.4173982302,
  'PM10': 0.6443906905,
  'PM2.5': 0.5004122871,
  'PSFC': 0.4956461178,
  'RH': 0.2854852068,
  'SO2': 0.4662876021,
  'TEMP': 0.3140151893,
  'lat': 35.97,
  'lon': 103.74},
 {'year': 2018,
  'name': '北京',
  'CO': 0.5805548392,
  'NO2': 0.8149669784,
  'O3': 0.2881787545,
  'PM10': 0.592548137,
  'PM2.5': 0.6795672756,
  'PSFC': 0.9892828319,
  'RH': 0.0231403352,
  'SO2': 0.2099376818,
  'TEMP': 0.5438569304,
  'lat': 39.97,
  'lon': 116.38},
 {'year': 2018,
  'name': '南京',
  'CO': 0.5431411151,
  'NO2': 0.7931024355,
  'O3': 0.3598726771,
  'PM10': 0.5341352037,
  'PM2.5': 0.5737805651,
  'PSFC': 0.9929483464,
  'RH': 0.6245005576,
  'SO2': 0.364465176,
  'TEMP': 0.6841126314,
  'lat': 32.09,
  'lon': 118.77},
 {'year': 2018,
  'name': '南宁',
  'CO': 0.7448737082,
  'NO2': 0.6913297685,
  'O3': 0.060892944,
  'PM10': 0.3878681819,
  'PM2.5': 0.4262263701,
  'PSFC': 0.954879266,
  'RH': 0.7239552875,
  'SO2': 0.4406600922,
  'TEMP': 0.9047701143,
  'lat': 22.91,
  'lon': 108.28},
 {'year': 2018,
  'name': '南昌',
  'CO': 0.6840954329,
  'NO2': 0.5551625568,
  'O3': 0.2906764207,
  'PM10': 0.4041273962,
  'PM2.5': 0.3499863345,
  'PSFC': 0.9902428597,
  'RH': 0.6883848383,
  'SO2': 0.3821953686,
  'TEMP': 0.7844587496,
  'lat': 28.68,
  'lon': 115.93},
 {'year': 2018,
  'name': '台北',
  'CO': 0.0053554589,
  'NO2': 0.2419800807,
  'O3': 0.4974105617,
  'PM10': 0.0880177152,
  'PM2.5': 0.1790634456,
  'PSFC': 0.9365652071,
  'RH': 0.9291246549,
  'SO2': 0.3308054183,
  'TEMP': 0.8847146094,
  'lat': 25.03,
  'lon': 121.52},
 {'year': 2018,
  'name': '合肥',
  'CO': 0.5647202675,
  'NO2': 0.721821842,
  'O3': 0.468192555,
  'PM10': 0.5264688214,
  'PM2.5': 0.6271950988,
  'PSFC': 0.99295398,
  'RH': 0.564982547,
  'SO2': 0.2569807967,
  'TEMP': 0.7020384706,
  'lat': 31.83,
  'lon': 117.28},
 {'year': 2018,
  'name': '呼和浩特',
  'CO': 0.760798483,
  'NO2': 0.6395054796,
  'O3': 0.3462303279,
  'PM10': 0.5988476182,
  'PM2.5': 0.4234466556,
  'PSFC': 0.6925147172,
  'RH': 0.1310064465,
  'SO2': 0.6058041847,
  'TEMP': 0.2866456404,
  'lat': 40.82,
  'lon': 111.68},
 {'year': 2018,
  'name': '哈尔滨',
  'CO': 0.5087495945,
  'NO2': 0.6544315981,
  'O3': 0.2545077684,
  'PM10': 0.4034771885,
  'PM2.5': 0.4619492629,
  'PSFC': 0.9505689965,
  'RH': 0.4972115206,
  'SO2': 0.6268302931,
  'TEMP': 0.1634768266,
  'lat': 45.71,
  'lon': 126.66},
 {'year': 2018,
  'name': '天津',
  'CO': 0.7995333716,
  'NO2': 0.8506786487,
  'O3': 0.3939043733,
  'PM10': 0.6789520334,
  'PM2.5': 0.7454327112,
  'PSFC': 1.0,
  'RH': 0.146058741,
  'SO2': 0.455945019,
  'TEMP': 0.5376757117,
  'lat': 39.09,
  'lon': 117.13},
 {'year': 2018,
  'name': '太原',
  'CO': 0.7508138993,
  'NO2': 0.8869262155,
  'O3': 0.3105238492,
  'PM10': 0.9139173235,
  'PM2.5': 0.7154174496,
  'PSFC': 0.7492788015,
  'RH': 0.1282900328,
  'SO2': 0.9203801639,
  'TEMP': 0.4247583,
  'lat': 37.93,
  'lon': 112.48},
 {'year': 2018,
  'name': '广州',
  'CO': 0.5641080772,
  'NO2': 0.8907029407,
  'O3': 0.1207703669,
  'PM10': 0.3692650404,
  'PM2.5': 0.436873572,
  'PSFC': 0.9820484866,
  'RH': 0.7380135104,
  'SO2': 0.3427917824,
  'TEMP': 0.931643375,
  'lat': 23.2,
  'lon': 113.26},
 {'year': 2018,
  'name': '成都',
  'CO': 0.6186268195,
  'NO2': 0.9414028289,
  'O3': 0.1028325446,
  'PM10': 0.5838498781,
  'PM2.5': 0.6720040296,
  'PSFC': 0.854562311,
  'RH': 0.5827066972,
  'SO2': 0.3516522108,
  'TEMP': 0.6898734649,
  'lat': 30.66,
  'lon': 104.13},
 {'year': 2018,
  'name': '拉萨',
  'CO': 0.0,
  'NO2': 0.0,
  'O3': 1.0,
  'PM10': 0.0,
  'PM2.5': 0.0,
  'PSFC': 0.0,
  'RH': 0.2845171823,
  'SO2': 0.0,
  'TEMP': 0.0,
  'lat': 30.01,
  'lon': 91.07},
 {'year': 2018,
  'name': '昆明',
  'CO': 0.5884056924,
  'NO2': 0.6143100562,
  'O3': 0.1881111135,
  'PM10': 0.3287956254,
  'PM2.5': 0.3181977166,
  'PSFC': 0.5047105434,
  'RH': 0.828298727,
  'SO2': 0.4585807596,
  'TEMP': 0.5674426806,
  'lat': 25.08,
  'lon': 102.69},
 {'year': 2018,
  'name': '杭州',
  'CO': 0.5717356918,
  'NO2': 0.7199090624,
  'O3': 0.2995560619,
  'PM10': 0.4272045313,
  'PM2.5': 0.4876092886,
  'PSFC': 0.9964997254,
  'RH': 0.8116445718,
  'SO2': 0.2968908397,
  'TEMP': 0.7073508321,
  'lat': 30.27,
  'lon': 120.24},
 {'year': 2018,
  'name': '武汉',
  'CO': 0.7312559221,
  'NO2': 0.8414665185,
  'O3': 0.1685912898,
  'PM10': 0.5407142883,
  'PM2.5': 0.6295907445,
  'PSFC': 0.9929866936,
  'RH': 0.5189807085,
  'SO2': 0.3692879414,
  'TEMP': 0.7477192361,
  'lat': 30.59,
  'lon': 114.25},
 {'year': 2018,
  'name': '沈阳',
  'CO': 0.7477034782,
  'NO2': 0.7519285118,
  'O3': 0.2752368078,
  'PM10': 0.515986073,
  'PM2.5': 0.5100565177,
  'PSFC': 0.9890758771,
  'RH': 0.297610047,
  'SO2': 0.8592287905,
  'TEMP': 0.3553691373,
  'lat': 41.81,
  'lon': 123.38},
 {'year': 2018,
  'name': '济南',
  'CO': 0.6399611752,
  'NO2': 0.7810127219,
  'O3': 0.6957878318,
  'PM10': 0.7902907342,
  'PM2.5': 0.6998810672,
  'PSFC': 0.9824302141,
  'RH': 0.1655099726,
  'SO2': 0.5528421626,
  'TEMP': 0.6228500771,
  'lat': 36.65,
  'lon': 116.95},
 {'year': 2018,
  'name': '海口',
  'CO': 0.2454224725,
  'NO2': 0.1302652317,
  'O3': 0.2707110423,
  'PM10': 0.1449113627,
  'PM2.5': 0.1607790782,
  'PSFC': 0.9803311196,
  'RH': 1.0,
  'SO2': 0.2043436814,
  'TEMP': 1.0,
  'lat': 20.02,
  'lon': 110.31},
 {'year': 2018,
  'name': '澳门',
  'CO': 0.2102794857,
  'NO2': 0.2843694531,
  'O3': 0.528715077,
  'PM10': 0.169909117,
  'PM2.5': 0.2374948692,
  'PSFC': 0.9864840575,
  'RH': 0.9716142128,
  'SO2': 0.2153325174,
  'TEMP': 0.9357060129,
  'lat': 22.12,
  'lon': 113.32},
 {'year': 2018,
  'name': '石家庄',
  'CO': 0.8683190224,
  'NO2': 0.8546389894,
  'O3': 0.4354277364,
  'PM10': 1.0,
  'PM2.5': 1.0,
  'PSFC': 0.9861316636,
  'RH': 0.0211735462,
  'SO2': 0.7515095093,
  'TEMP': 0.6027735452,
  'lat': 38.07,
  'lon': 114.56},
 {'year': 2018,
  'name': '福州',
  'CO': 0.4372681736,
  'NO2': 0.4694782892,
  'O3': 0.3739527094,
  'PM10': 0.2785702407,
  'PM2.5': 0.2759403547,
  'PSFC': 0.9322896103,
  'RH': 0.9066194698,
  'SO2': 0.2995398722,
  'TEMP': 0.7829070726,
  'lat': 26.14,
  'lon': 119.28},
 {'year': 2018,
  'name': '西宁',
  'CO': 1.0,
  'NO2': 0.5084058229,
  'O3': 0.432599471,
  'PM10': 0.6312764389,
  'PM2.5': 0.5252619553,
  'PSFC': 0.4048519003,
  'RH': 0.3087552084,
  'SO2': 0.4833402727,
  'TEMP': 0.2170954136,
  'lat': 36.61,
  'lon': 101.7},
 {'year': 2018,
  'name': '西安',
  'CO': 0.9012942964,
  'NO2': 1.0,
  'O3': 0.2325868384,
  'PM10': 0.88853503,
  'PM2.5': 0.8381514563,
  'PSFC': 0.8988367557,
  'RH': 0.153951165,
  'SO2': 0.4886839662,
  'TEMP': 0.672850606,
  'lat': 34.28,
  'lon': 108.87},
 {'year': 2018,
  'name': '贵阳',
  'CO': 0.3507758664,
  'NO2': 0.330214813,
  'O3': 0.2564826644,
  'PM10': 0.3088279872,
  'PM2.5': 0.3572234762,
  'PSFC': 0.6943136875,
  'RH': 0.9458808052,
  'SO2': 0.3412990443,
  'TEMP': 0.5771465991,
  'lat': 26.58,
  'lon': 106.74},
 {'year': 2018,
  'name': '郑州',
  'CO': 0.762355821,
  'NO2': 0.7826069937,
  'O3': 0.5320895444,
  'PM10': 0.833039638,
  'PM2.5': 0.8653524086,
  'PSFC': 0.9676732136,
  'RH': 0.1831746772,
  'SO2': 0.4803217043,
  'TEMP': 0.6537099723,
  'lat': 34.73,
  'lon': 113.7},
 {'year': 2018,
  'name': '重庆',
  'CO': 0.6179994252,
  'NO2': 0.7749116208,
  'O3': 0.0,
  'PM10': 0.4041727137,
  'PM2.5': 0.4747847317,
  'PSFC': 0.9160580038,
  'RH': 0.5799984464,
  'SO2': 0.3682520732,
  'TEMP': 0.7884913168,
  'lat': 29.57,
  'lon': 106.48},
 {'year': 2018,
  'name': '银川',
  'CO': 0.6148800973,
  'NO2': 0.6461361215,
  'O3': 0.5426304457,
  'PM10': 0.85529863,
  'PM2.5': 0.524337637,
  'PSFC': 0.7101406471,
  'RH': 0.0,
  'SO2': 1.0,
  'TEMP': 0.4580666099,
  'lat': 38.41,
  'lon': 106.3},
 {'year': 2018,
  'name': '长春',
  'CO': 0.5990850108,
  'NO2': 0.6708244203,
  'O3': 0.1946783525,
  'PM10': 0.4216082544,
  'PM2.5': 0.3974389863,
  'PSFC': 0.9367553038,
  'RH': 0.422267379,
  'SO2': 0.5318325444,
  'TEMP': 0.2306114346,
  'lat': 43.86,
  'lon': 125.37},
 {'year': 2018,
  'name': '长沙',
  'CO': 0.6098999743,
  'NO2': 0.5789839141,
  'O3': 0.3328181136,
  'PM10': 0.4784046334,
  'PM2.5': 0.606256385,
  'PSFC': 0.9822397527,
  'RH': 0.6897636645,
  'SO2': 0.337862557,
  'TEMP': 0.7612422409,
  'lat': 28.23,
  'lon': 112.94},
 {'year': 2018,
  'name': '香港',
  'CO': 0.2416415979,
  'NO2': 0.4419004364,
  'O3': 0.3619658806,
  'PM10': 0.1810605459,
  'PM2.5': 0.2415397981,
  'PSFC': 0.9717581327,
  'RH': 0.9475505479,
  'SO2': 0.2143004515,
  'TEMP': 0.9112103178,
  'lat': 22.46,
  'lon': 114.08}]

In [46]:
nn_jd = {'name':'地点'}

In [37]:
location = []
for i in jd:
    temp = {}
    temp['name'] = i['name']
    temp['lat'] = i['lat']
    temp['log'] = i['lon']
    temp['name'] = i['name']
    temp['group'] = 'A'
    temp['size'] = i['PM2.5']
    location.append(temp.copy())
    temp['group'] = 'B'
    temp['size'] = i['PM10']
    location.append(temp.copy())
    temp['group'] = 'C'
    temp['size'] = i['SO2']
    location.append(temp.copy())
    temp['group'] = 'D'
    temp['size'] = i['NO2']
    location.append(temp.copy())
    temp['group'] = 'E'
    temp['size'] = i['CO']
    location.append(temp.copy())
    temp['group'] = 'F'
    temp['size'] = i['O3']
    location.append(temp.copy())

In [38]:
location

[{'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'A',
  'size': 0.4174413606},
 {'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'B',
  'size': 0.3194565538},
 {'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'C',
  'size': 0.3218215916},
 {'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'D',
  'size': 0.7078426127},
 {'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'E',
  'size': 0.3706397969},
 {'name': '上海',
  'lat': 31.2,
  'log': 121.53,
  'group': 'F',
  'size': 0.5230689973},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'A',
  'size': 0.331636761},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'B',
  'size': 0.3249112082},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'C',
  'size': 0.1224007653},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'D',
  'size': 0.4279440898},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'E',
  'size': 0.2831714234},
 {'name': '乌鲁木齐',
  'lat': 43.71,
  'log': 87.67,
  'group': 'F',
  'size': 0.4662159962},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'A',
  'size': 0.5004122871},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'B',
  'size': 0.6443906905},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'C',
  'size': 0.4662876021},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'D',
  'size': 0.5859411843},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'E',
  'size': 0.5971175604},
 {'name': '兰州',
  'lat': 35.97,
  'log': 103.74,
  'group': 'F',
  'size': 0.4173982302},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'A',
  'size': 0.6795672756},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'B',
  'size': 0.592548137},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'C',
  'size': 0.2099376818},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'D',
  'size': 0.8149669784},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'E',
  'size': 0.5805548392},
 {'name': '北京',
  'lat': 39.97,
  'log': 116.38,
  'group': 'F',
  'size': 0.2881787545},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'A',
  'size': 0.5737805651},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'B',
  'size': 0.5341352037},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'C',
  'size': 0.364465176},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'D',
  'size': 0.7931024355},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'E',
  'size': 0.5431411151},
 {'name': '南京',
  'lat': 32.09,
  'log': 118.77,
  'group': 'F',
  'size': 0.3598726771},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'A',
  'size': 0.4262263701},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'B',
  'size': 0.3878681819},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'C',
  'size': 0.4406600922},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'D',
  'size': 0.6913297685},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'E',
  'size': 0.7448737082},
 {'name': '南宁',
  'lat': 22.91,
  'log': 108.28,
  'group': 'F',
  'size': 0.060892944},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'A',
  'size': 0.3499863345},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'B',
  'size': 0.4041273962},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'C',
  'size': 0.3821953686},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'D',
  'size': 0.5551625568},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'E',
  'size': 0.6840954329},
 {'name': '南昌',
  'lat': 28.68,
  'log': 115.93,
  'group': 'F',
  'size': 0.2906764207},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'A',
  'size': 0.1790634456},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'B',
  'size': 0.0880177152},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'C',
  'size': 0.3308054183},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'D',
  'size': 0.2419800807},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'E',
  'size': 0.0053554589},
 {'name': '台北',
  'lat': 25.03,
  'log': 121.52,
  'group': 'F',
  'size': 0.4974105617},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'A',
  'size': 0.6271950988},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'B',
  'size': 0.5264688214},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'C',
  'size': 0.2569807967},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'D',
  'size': 0.721821842},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'E',
  'size': 0.5647202675},
 {'name': '合肥',
  'lat': 31.83,
  'log': 117.28,
  'group': 'F',
  'size': 0.468192555},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'A',
  'size': 0.4234466556},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'B',
  'size': 0.5988476182},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'C',
  'size': 0.6058041847},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'D',
  'size': 0.6395054796},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'E',
  'size': 0.760798483},
 {'name': '呼和浩特',
  'lat': 40.82,
  'log': 111.68,
  'group': 'F',
  'size': 0.3462303279},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'A',
  'size': 0.4619492629},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'B',
  'size': 0.4034771885},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'C',
  'size': 0.6268302931},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'D',
  'size': 0.6544315981},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'E',
  'size': 0.5087495945},
 {'name': '哈尔滨',
  'lat': 45.71,
  'log': 126.66,
  'group': 'F',
  'size': 0.2545077684},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'A',
  'size': 0.7454327112},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'B',
  'size': 0.6789520334},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'C',
  'size': 0.455945019},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'D',
  'size': 0.8506786487},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'E',
  'size': 0.7995333716},
 {'name': '天津',
  'lat': 39.09,
  'log': 117.13,
  'group': 'F',
  'size': 0.3939043733},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'A',
  'size': 0.7154174496},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'B',
  'size': 0.9139173235},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'C',
  'size': 0.9203801639},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'D',
  'size': 0.8869262155},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'E',
  'size': 0.7508138993},
 {'name': '太原',
  'lat': 37.93,
  'log': 112.48,
  'group': 'F',
  'size': 0.3105238492},
 {'name': '广州', 'lat': 23.2, 'log': 113.26, 'group': 'A', 'size': 0.436873572},
 {'name': '广州',
  'lat': 23.2,
  'log': 113.26,
  'group': 'B',
  'size': 0.3692650404},
 {'name': '广州',
  'lat': 23.2,
  'log': 113.26,
  'group': 'C',
  'size': 0.3427917824},
 {'name': '广州',
  'lat': 23.2,
  'log': 113.26,
  'group': 'D',
  'size': 0.8907029407},
 {'name': '广州',
  'lat': 23.2,
  'log': 113.26,
  'group': 'E',
  'size': 0.5641080772},
 {'name': '广州',
  'lat': 23.2,
  'log': 113.26,
  'group': 'F',
  'size': 0.1207703669},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'A',
  'size': 0.6720040296},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'B',
  'size': 0.5838498781},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'C',
  'size': 0.3516522108},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'D',
  'size': 0.9414028289},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'E',
  'size': 0.6186268195},
 {'name': '成都',
  'lat': 30.66,
  'log': 104.13,
  'group': 'F',
  'size': 0.1028325446},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'A', 'size': 0.0},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'B', 'size': 0.0},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'C', 'size': 0.0},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'D', 'size': 0.0},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'E', 'size': 0.0},
 {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'F', 'size': 1.0},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'A',
  'size': 0.3181977166},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'B',
  'size': 0.3287956254},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'C',
  'size': 0.4585807596},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'D',
  'size': 0.6143100562},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'E',
  'size': 0.5884056924},
 {'name': '昆明',
  'lat': 25.08,
  'log': 102.69,
  'group': 'F',
  'size': 0.1881111135},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'A',
  'size': 0.4876092886},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'B',
  'size': 0.4272045313},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'C',
  'size': 0.2968908397},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'D',
  'size': 0.7199090624},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'E',
  'size': 0.5717356918},
 {'name': '杭州',
  'lat': 30.27,
  'log': 120.24,
  'group': 'F',
  'size': 0.2995560619},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'A',
  'size': 0.6295907445},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'B',
  'size': 0.5407142883},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'C',
  'size': 0.3692879414},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'D',
  'size': 0.8414665185},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'E',
  'size': 0.7312559221},
 {'name': '武汉',
  'lat': 30.59,
  'log': 114.25,
  'group': 'F',
  'size': 0.1685912898},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'A',
  'size': 0.5100565177},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'B',
  'size': 0.515986073},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'C',
  'size': 0.8592287905},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'D',
  'size': 0.7519285118},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'E',
  'size': 0.7477034782},
 {'name': '沈阳',
  'lat': 41.81,
  'log': 123.38,
  'group': 'F',
  'size': 0.2752368078},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'A',
  'size': 0.6998810672},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'B',
  'size': 0.7902907342},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'C',
  'size': 0.5528421626},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'D',
  'size': 0.7810127219},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'E',
  'size': 0.6399611752},
 {'name': '济南',
  'lat': 36.65,
  'log': 116.95,
  'group': 'F',
  'size': 0.6957878318},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'A',
  'size': 0.1607790782},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'B',
  'size': 0.1449113627},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'C',
  'size': 0.2043436814},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'D',
  'size': 0.1302652317},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'E',
  'size': 0.2454224725},
 {'name': '海口',
  'lat': 20.02,
  'log': 110.31,
  'group': 'F',
  'size': 0.2707110423},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'A',
  'size': 0.2374948692},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'B',
  'size': 0.169909117},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'C',
  'size': 0.2153325174},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'D',
  'size': 0.2843694531},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'E',
  'size': 0.2102794857},
 {'name': '澳门',
  'lat': 22.12,
  'log': 113.32,
  'group': 'F',
  'size': 0.528715077},
 {'name': '石家庄', 'lat': 38.07, 'log': 114.56, 'group': 'A', 'size': 1.0},
 {'name': '石家庄', 'lat': 38.07, 'log': 114.56, 'group': 'B', 'size': 1.0},
 {'name': '石家庄',
  'lat': 38.07,
  'log': 114.56,
  'group': 'C',
  'size': 0.7515095093},
 {'name': '石家庄',
  'lat': 38.07,
  'log': 114.56,
  'group': 'D',
  'size': 0.8546389894},
 {'name': '石家庄',
  'lat': 38.07,
  'log': 114.56,
  'group': 'E',
  'size': 0.8683190224},
 {'name': '石家庄',
  'lat': 38.07,
  'log': 114.56,
  'group': 'F',
  'size': 0.4354277364},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'A',
  'size': 0.2759403547},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'B',
  'size': 0.2785702407},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'C',
  'size': 0.2995398722},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'D',
  'size': 0.4694782892},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'E',
  'size': 0.4372681736},
 {'name': '福州',
  'lat': 26.14,
  'log': 119.28,
  'group': 'F',
  'size': 0.3739527094},
 {'name': '西宁',
  'lat': 36.61,
  'log': 101.7,
  'group': 'A',
  'size': 0.5252619553},
 {'name': '西宁',
  'lat': 36.61,
  'log': 101.7,
  'group': 'B',
  'size': 0.6312764389},
 {'name': '西宁',
  'lat': 36.61,
  'log': 101.7,
  'group': 'C',
  'size': 0.4833402727},
 {'name': '西宁',
  'lat': 36.61,
  'log': 101.7,
  'group': 'D',
  'size': 0.5084058229},
 {'name': '西宁', 'lat': 36.61, 'log': 101.7, 'group': 'E', 'size': 1.0},
 {'name': '西宁', 'lat': 36.61, 'log': 101.7, 'group': 'F', 'size': 0.432599471},
 {'name': '西安',
  'lat': 34.28,
  'log': 108.87,
  'group': 'A',
  'size': 0.8381514563},
 {'name': '西安', 'lat': 34.28, 'log': 108.87, 'group': 'B', 'size': 0.88853503},
 {'name': '西安',
  'lat': 34.28,
  'log': 108.87,
  'group': 'C',
  'size': 0.4886839662},
 {'name': '西安', 'lat': 34.28, 'log': 108.87, 'group': 'D', 'size': 1.0},
 {'name': '西安',
  'lat': 34.28,
  'log': 108.87,
  'group': 'E',
  'size': 0.9012942964},
 {'name': '西安',
  'lat': 34.28,
  'log': 108.87,
  'group': 'F',
  'size': 0.2325868384},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'A',
  'size': 0.3572234762},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'B',
  'size': 0.3088279872},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'C',
  'size': 0.3412990443},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'D',
  'size': 0.330214813},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'E',
  'size': 0.3507758664},
 {'name': '贵阳',
  'lat': 26.58,
  'log': 106.74,
  'group': 'F',
  'size': 0.2564826644},
 {'name': '郑州',
  'lat': 34.73,
  'log': 113.7,
  'group': 'A',
  'size': 0.8653524086},
 {'name': '郑州', 'lat': 34.73, 'log': 113.7, 'group': 'B', 'size': 0.833039638},
 {'name': '郑州',
  'lat': 34.73,
  'log': 113.7,
  'group': 'C',
  'size': 0.4803217043},
 {'name': '郑州',
  'lat': 34.73,
  'log': 113.7,
  'group': 'D',
  'size': 0.7826069937},
 {'name': '郑州', 'lat': 34.73, 'log': 113.7, 'group': 'E', 'size': 0.762355821},
 {'name': '郑州',
  'lat': 34.73,
  'log': 113.7,
  'group': 'F',
  'size': 0.5320895444},
 {'name': '重庆',
  'lat': 29.57,
  'log': 106.48,
  'group': 'A',
  'size': 0.4747847317},
 {'name': '重庆',
  'lat': 29.57,
  'log': 106.48,
  'group': 'B',
  'size': 0.4041727137},
 {'name': '重庆',
  'lat': 29.57,
  'log': 106.48,
  'group': 'C',
  'size': 0.3682520732},
 {'name': '重庆',
  'lat': 29.57,
  'log': 106.48,
  'group': 'D',
  'size': 0.7749116208},
 {'name': '重庆',
  'lat': 29.57,
  'log': 106.48,
  'group': 'E',
  'size': 0.6179994252},
 {'name': '重庆', 'lat': 29.57, 'log': 106.48, 'group': 'F', 'size': 0.0},
 {'name': '银川', 'lat': 38.41, 'log': 106.3, 'group': 'A', 'size': 0.524337637},
 {'name': '银川', 'lat': 38.41, 'log': 106.3, 'group': 'B', 'size': 0.85529863},
 {'name': '银川', 'lat': 38.41, 'log': 106.3, 'group': 'C', 'size': 1.0},
 {'name': '银川',
  'lat': 38.41,
  'log': 106.3,
  'group': 'D',
  'size': 0.6461361215},
 {'name': '银川',
  'lat': 38.41,
  'log': 106.3,
  'group': 'E',
  'size': 0.6148800973},
 {'name': '银川',
  'lat': 38.41,
  'log': 106.3,
  'group': 'F',
  'size': 0.5426304457},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'A',
  'size': 0.3974389863},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'B',
  'size': 0.4216082544},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'C',
  'size': 0.5318325444},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'D',
  'size': 0.6708244203},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'E',
  'size': 0.5990850108},
 {'name': '长春',
  'lat': 43.86,
  'log': 125.37,
  'group': 'F',
  'size': 0.1946783525},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'A',
  'size': 0.606256385},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'B',
  'size': 0.4784046334},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'C',
  'size': 0.337862557},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'D',
  'size': 0.5789839141},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'E',
  'size': 0.6098999743},
 {'name': '长沙',
  'lat': 28.23,
  'log': 112.94,
  'group': 'F',
  'size': 0.3328181136},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'A',
  'size': 0.2415397981},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'B',
  'size': 0.1810605459},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'C',
  'size': 0.2143004515},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'D',
  'size': 0.4419004364},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'E',
  'size': 0.2416415979},
 {'name': '香港',
  'lat': 22.46,
  'log': 114.08,
  'group': 'F',
  'size': 0.3619658806}]

In [47]:
nn_jd['location'] = location

In [48]:
nn_jd

{'name': '地点',
 'location': [{'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'A',
   'size': 0.4174413606},
  {'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'B',
   'size': 0.3194565538},
  {'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'C',
   'size': 0.3218215916},
  {'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'D',
   'size': 0.7078426127},
  {'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'E',
   'size': 0.3706397969},
  {'name': '上海',
   'lat': 31.2,
   'log': 121.53,
   'group': 'F',
   'size': 0.5230689973},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'A',
   'size': 0.331636761},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'B',
   'size': 0.3249112082},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'C',
   'size': 0.1224007653},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'D',
   'size': 0.4279440898},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'E',
   'size': 0.2831714234},
  {'name': '乌鲁木齐',
   'lat': 43.71,
   'log': 87.67,
   'group': 'F',
   'size': 0.4662159962},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'A',
   'size': 0.5004122871},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'B',
   'size': 0.6443906905},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'C',
   'size': 0.4662876021},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'D',
   'size': 0.5859411843},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'E',
   'size': 0.5971175604},
  {'name': '兰州',
   'lat': 35.97,
   'log': 103.74,
   'group': 'F',
   'size': 0.4173982302},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'A',
   'size': 0.6795672756},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'B',
   'size': 0.592548137},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'C',
   'size': 0.2099376818},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'D',
   'size': 0.8149669784},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'E',
   'size': 0.5805548392},
  {'name': '北京',
   'lat': 39.97,
   'log': 116.38,
   'group': 'F',
   'size': 0.2881787545},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'A',
   'size': 0.5737805651},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'B',
   'size': 0.5341352037},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'C',
   'size': 0.364465176},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'D',
   'size': 0.7931024355},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'E',
   'size': 0.5431411151},
  {'name': '南京',
   'lat': 32.09,
   'log': 118.77,
   'group': 'F',
   'size': 0.3598726771},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'A',
   'size': 0.4262263701},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'B',
   'size': 0.3878681819},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'C',
   'size': 0.4406600922},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'D',
   'size': 0.6913297685},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'E',
   'size': 0.7448737082},
  {'name': '南宁',
   'lat': 22.91,
   'log': 108.28,
   'group': 'F',
   'size': 0.060892944},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'A',
   'size': 0.3499863345},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'B',
   'size': 0.4041273962},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'C',
   'size': 0.3821953686},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'D',
   'size': 0.5551625568},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'E',
   'size': 0.6840954329},
  {'name': '南昌',
   'lat': 28.68,
   'log': 115.93,
   'group': 'F',
   'size': 0.2906764207},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'A',
   'size': 0.1790634456},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'B',
   'size': 0.0880177152},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'C',
   'size': 0.3308054183},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'D',
   'size': 0.2419800807},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'E',
   'size': 0.0053554589},
  {'name': '台北',
   'lat': 25.03,
   'log': 121.52,
   'group': 'F',
   'size': 0.4974105617},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'A',
   'size': 0.6271950988},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'B',
   'size': 0.5264688214},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'C',
   'size': 0.2569807967},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'D',
   'size': 0.721821842},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'E',
   'size': 0.5647202675},
  {'name': '合肥',
   'lat': 31.83,
   'log': 117.28,
   'group': 'F',
   'size': 0.468192555},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'A',
   'size': 0.4234466556},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'B',
   'size': 0.5988476182},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'C',
   'size': 0.6058041847},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'D',
   'size': 0.6395054796},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'E',
   'size': 0.760798483},
  {'name': '呼和浩特',
   'lat': 40.82,
   'log': 111.68,
   'group': 'F',
   'size': 0.3462303279},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'A',
   'size': 0.4619492629},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'B',
   'size': 0.4034771885},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'C',
   'size': 0.6268302931},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'D',
   'size': 0.6544315981},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'E',
   'size': 0.5087495945},
  {'name': '哈尔滨',
   'lat': 45.71,
   'log': 126.66,
   'group': 'F',
   'size': 0.2545077684},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'A',
   'size': 0.7454327112},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'B',
   'size': 0.6789520334},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'C',
   'size': 0.455945019},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'D',
   'size': 0.8506786487},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'E',
   'size': 0.7995333716},
  {'name': '天津',
   'lat': 39.09,
   'log': 117.13,
   'group': 'F',
   'size': 0.3939043733},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'A',
   'size': 0.7154174496},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'B',
   'size': 0.9139173235},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'C',
   'size': 0.9203801639},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'D',
   'size': 0.8869262155},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'E',
   'size': 0.7508138993},
  {'name': '太原',
   'lat': 37.93,
   'log': 112.48,
   'group': 'F',
   'size': 0.3105238492},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'A',
   'size': 0.436873572},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'B',
   'size': 0.3692650404},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'C',
   'size': 0.3427917824},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'D',
   'size': 0.8907029407},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'E',
   'size': 0.5641080772},
  {'name': '广州',
   'lat': 23.2,
   'log': 113.26,
   'group': 'F',
   'size': 0.1207703669},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'A',
   'size': 0.6720040296},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'B',
   'size': 0.5838498781},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'C',
   'size': 0.3516522108},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'D',
   'size': 0.9414028289},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'E',
   'size': 0.6186268195},
  {'name': '成都',
   'lat': 30.66,
   'log': 104.13,
   'group': 'F',
   'size': 0.1028325446},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'A', 'size': 0.0},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'B', 'size': 0.0},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'C', 'size': 0.0},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'D', 'size': 0.0},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'E', 'size': 0.0},
  {'name': '拉萨', 'lat': 30.01, 'log': 91.07, 'group': 'F', 'size': 1.0},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'A',
   'size': 0.3181977166},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'B',
   'size': 0.3287956254},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'C',
   'size': 0.4585807596},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'D',
   'size': 0.6143100562},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'E',
   'size': 0.5884056924},
  {'name': '昆明',
   'lat': 25.08,
   'log': 102.69,
   'group': 'F',
   'size': 0.1881111135},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'A',
   'size': 0.4876092886},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'B',
   'size': 0.4272045313},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'C',
   'size': 0.2968908397},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'D',
   'size': 0.7199090624},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'E',
   'size': 0.5717356918},
  {'name': '杭州',
   'lat': 30.27,
   'log': 120.24,
   'group': 'F',
   'size': 0.2995560619},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'A',
   'size': 0.6295907445},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'B',
   'size': 0.5407142883},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'C',
   'size': 0.3692879414},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'D',
   'size': 0.8414665185},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'E',
   'size': 0.7312559221},
  {'name': '武汉',
   'lat': 30.59,
   'log': 114.25,
   'group': 'F',
   'size': 0.1685912898},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'A',
   'size': 0.5100565177},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'B',
   'size': 0.515986073},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'C',
   'size': 0.8592287905},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'D',
   'size': 0.7519285118},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'E',
   'size': 0.7477034782},
  {'name': '沈阳',
   'lat': 41.81,
   'log': 123.38,
   'group': 'F',
   'size': 0.2752368078},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'A',
   'size': 0.6998810672},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'B',
   'size': 0.7902907342},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'C',
   'size': 0.5528421626},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'D',
   'size': 0.7810127219},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'E',
   'size': 0.6399611752},
  {'name': '济南',
   'lat': 36.65,
   'log': 116.95,
   'group': 'F',
   'size': 0.6957878318},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'A',
   'size': 0.1607790782},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'B',
   'size': 0.1449113627},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'C',
   'size': 0.2043436814},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'D',
   'size': 0.1302652317},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'E',
   'size': 0.2454224725},
  {'name': '海口',
   'lat': 20.02,
   'log': 110.31,
   'group': 'F',
   'size': 0.2707110423},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'A',
   'size': 0.2374948692},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'B',
   'size': 0.169909117},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'C',
   'size': 0.2153325174},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'D',
   'size': 0.2843694531},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'E',
   'size': 0.2102794857},
  {'name': '澳门',
   'lat': 22.12,
   'log': 113.32,
   'group': 'F',
   'size': 0.528715077},
  {'name': '石家庄', 'lat': 38.07, 'log': 114.56, 'group': 'A', 'size': 1.0},
  {'name': '石家庄', 'lat': 38.07, 'log': 114.56, 'group': 'B', 'size': 1.0},
  {'name': '石家庄',
   'lat': 38.07,
   'log': 114.56,
   'group': 'C',
   'size': 0.7515095093},
  {'name': '石家庄',
   'lat': 38.07,
   'log': 114.56,
   'group': 'D',
   'size': 0.8546389894},
  {'name': '石家庄',
   'lat': 38.07,
   'log': 114.56,
   'group': 'E',
   'size': 0.8683190224},
  {'name': '石家庄',
   'lat': 38.07,
   'log': 114.56,
   'group': 'F',
   'size': 0.4354277364},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'A',
   'size': 0.2759403547},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'B',
   'size': 0.2785702407},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'C',
   'size': 0.2995398722},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'D',
   'size': 0.4694782892},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'E',
   'size': 0.4372681736},
  {'name': '福州',
   'lat': 26.14,
   'log': 119.28,
   'group': 'F',
   'size': 0.3739527094},
  {'name': '西宁',
   'lat': 36.61,
   'log': 101.7,
   'group': 'A',
   'size': 0.5252619553},
  {'name': '西宁',
   'lat': 36.61,
   'log': 101.7,
   'group': 'B',
   'size': 0.6312764389},
  {'name': '西宁',
   'lat': 36.61,
   'log': 101.7,
   'group': 'C',
   'size': 0.4833402727},
  {'name': '西宁',
   'lat': 36.61,
   'log': 101.7,
   'group': 'D',
   'size': 0.5084058229},
  {'name': '西宁', 'lat': 36.61, 'log': 101.7, 'group': 'E', 'size': 1.0},
  {'name': '西宁',
   'lat': 36.61,
   'log': 101.7,
   'group': 'F',
   'size': 0.432599471},
  {'name': '西安',
   'lat': 34.28,
   'log': 108.87,
   'group': 'A',
   'size': 0.8381514563},
  {'name': '西安',
   'lat': 34.28,
   'log': 108.87,
   'group': 'B',
   'size': 0.88853503},
  {'name': '西安',
   'lat': 34.28,
   'log': 108.87,
   'group': 'C',
   'size': 0.4886839662},
  {'name': '西安', 'lat': 34.28, 'log': 108.87, 'group': 'D', 'size': 1.0},
  {'name': '西安',
   'lat': 34.28,
   'log': 108.87,
   'group': 'E',
   'size': 0.9012942964},
  {'name': '西安',
   'lat': 34.28,
   'log': 108.87,
   'group': 'F',
   'size': 0.2325868384},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'A',
   'size': 0.3572234762},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'B',
   'size': 0.3088279872},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'C',
   'size': 0.3412990443},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'D',
   'size': 0.330214813},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'E',
   'size': 0.3507758664},
  {'name': '贵阳',
   'lat': 26.58,
   'log': 106.74,
   'group': 'F',
   'size': 0.2564826644},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'A',
   'size': 0.8653524086},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'B',
   'size': 0.833039638},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'C',
   'size': 0.4803217043},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'D',
   'size': 0.7826069937},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'E',
   'size': 0.762355821},
  {'name': '郑州',
   'lat': 34.73,
   'log': 113.7,
   'group': 'F',
   'size': 0.5320895444},
  {'name': '重庆',
   'lat': 29.57,
   'log': 106.48,
   'group': 'A',
   'size': 0.4747847317},
  {'name': '重庆',
   'lat': 29.57,
   'log': 106.48,
   'group': 'B',
   'size': 0.4041727137},
  {'name': '重庆',
   'lat': 29.57,
   'log': 106.48,
   'group': 'C',
   'size': 0.3682520732},
  {'name': '重庆',
   'lat': 29.57,
   'log': 106.48,
   'group': 'D',
   'size': 0.7749116208},
  {'name': '重庆',
   'lat': 29.57,
   'log': 106.48,
   'group': 'E',
   'size': 0.6179994252},
  {'name': '重庆', 'lat': 29.57, 'log': 106.48, 'group': 'F', 'size': 0.0},
  {'name': '银川',
   'lat': 38.41,
   'log': 106.3,
   'group': 'A',
   'size': 0.524337637},
  {'name': '银川', 'lat': 38.41, 'log': 106.3, 'group': 'B', 'size': 0.85529863},
  {'name': '银川', 'lat': 38.41, 'log': 106.3, 'group': 'C', 'size': 1.0},
  {'name': '银川',
   'lat': 38.41,
   'log': 106.3,
   'group': 'D',
   'size': 0.6461361215},
  {'name': '银川',
   'lat': 38.41,
   'log': 106.3,
   'group': 'E',
   'size': 0.6148800973},
  {'name': '银川',
   'lat': 38.41,
   'log': 106.3,
   'group': 'F',
   'size': 0.5426304457},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'A',
   'size': 0.3974389863},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'B',
   'size': 0.4216082544},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'C',
   'size': 0.5318325444},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'D',
   'size': 0.6708244203},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'E',
   'size': 0.5990850108},
  {'name': '长春',
   'lat': 43.86,
   'log': 125.37,
   'group': 'F',
   'size': 0.1946783525},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'A',
   'size': 0.606256385},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'B',
   'size': 0.4784046334},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'C',
   'size': 0.337862557},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'D',
   'size': 0.5789839141},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'E',
   'size': 0.6098999743},
  {'name': '长沙',
   'lat': 28.23,
   'log': 112.94,
   'group': 'F',
   'size': 0.3328181136},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'A',
   'size': 0.2415397981},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'B',
   'size': 0.1810605459},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'C',
   'size': 0.2143004515},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'D',
   'size': 0.4419004364},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'E',
   'size': 0.2416415979},
  {'name': '香港',
   'lat': 22.46,
   'log': 114.08,
   'group': 'F',
   'size': 0.3619658806}]}

In [53]:
nn_jd = json.dumps(nn_jd,ensure_ascii=False )

In [54]:
fh = open('2018.json', 'w', encoding='utf-8')
jd = fh.write(nn_jd)
fh.close()